// Generated by Haxe 4.0.5
package connect.models;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Country extends connect.models.IdModel
{
	public Country(haxe.lang.EmptyObject empty)
	{
		//line 11 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/models/Country.hx"
		super(haxe.lang.EmptyObject.EMPTY);
	}
	
	
	public Country()
	{
		//line 103 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/models/Model.hx"
		super(haxe.lang.EmptyObject.EMPTY);
		//line 103 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/models/Model.hx"
		connect.models.Country.__hx_ctor_connect_models_Country(this);
	}
	
	
	protected static void __hx_ctor_connect_models_Country(connect.models.Country __hx_this)
	{
		//line 103 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/models/Model.hx"
		connect.models.IdModel.__hx_ctor_connect_models_IdModel(__hx_this);
	}
	
	
	public java.lang.String name;
	
	public java.lang.String icon;
	
	public java.lang.String zone;
	
	@Override public java.lang.Object __hx_setField(java.lang.String field, java.lang.Object value, boolean handleProperties)
	{
		//line 11 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/models/Country.hx"
		{
			//line 11 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/models/Country.hx"
			boolean __temp_executeDef1 = true;
			//line 11 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/models/Country.hx"
			if (( field != null )) 
			{
				//line 11 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/models/Country.hx"
				switch (field.hashCode())
				{
					case 3744684:
					{
						//line 11 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/models/Country.hx"
						if (field.equals("zone")) 
						{
							//line 11 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/models/Country.hx"
							__temp_executeDef1 = false;
							//line 11 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/models/Country.hx"
							this.zone = haxe.lang.Runtime.toString(value);
							//line 11 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/models/Country.hx"
							return value;
						}
						
						//line 11 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/models/Country.hx"
						break;
					}
					
					
					case 3373707:
					{
						//line 11 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/models/Country.hx"
						if (field.equals("name")) 
						{
							//line 11 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/models/Country.hx"
							__temp_executeDef1 = false;
							//line 11 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/models/Country.hx"
							this.name = haxe.lang.Runtime.toString(value);
							//line 11 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/models/Country.hx"
							return value;
						}
						
						//line 11 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/models/Country.hx"
						break;
					}
					
					
					case 3226745:
					{
						//line 11 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/models/Country.hx"
						if (field.equals("icon")) 
						{
							//line 11 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/models/Country.hx"
							__temp_executeDef1 = false;
							//line 11 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/models/Country.hx"
							this.icon = haxe.lang.Runtime.toString(value);
							//line 11 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/models/Country.hx"
							return value;
						}
						
						//line 11 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/models/Country.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 11 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/models/Country.hx"
			if (__temp_executeDef1) 
			{
				//line 11 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/models/Country.hx"
				return super.__hx_setField(field, value, handleProperties);
			}
			else
			{
				//line 11 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/models/Country.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 11 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/models/Country.hx"
		{
			//line 11 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/models/Country.hx"
			boolean __temp_executeDef1 = true;
			//line 11 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/models/Country.hx"
			if (( field != null )) 
			{
				//line 11 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/models/Country.hx"
				switch (field.hashCode())
				{
					case 3744684:
					{
						//line 11 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/models/Country.hx"
						if (field.equals("zone")) 
						{
							//line 11 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/models/Country.hx"
							__temp_executeDef1 = false;
							//line 11 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/models/Country.hx"
							return this.zone;
						}
						
						//line 11 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/models/Country.hx"
						break;
					}
					
					
					case 3373707:
					{
						//line 11 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/models/Country.hx"
						if (field.equals("name")) 
						{
							//line 11 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/models/Country.hx"
							__temp_executeDef1 = false;
							//line 11 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/models/Country.hx"
							return this.name;
						}
						
						//line 11 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/models/Country.hx"
						break;
					}
					
					
					case 3226745:
					{
						//line 11 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/models/Country.hx"
						if (field.equals("icon")) 
						{
							//line 11 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/models/Country.hx"
							__temp_executeDef1 = false;
							//line 11 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/models/Country.hx"
							return this.icon;
						}
						
						//line 11 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/models/Country.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 11 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/models/Country.hx"
			if (__temp_executeDef1) 
			{
				//line 11 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/models/Country.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 11 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/models/Country.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<java.lang.String> baseArr)
	{
		//line 11 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/models/Country.hx"
		baseArr.push("zone");
		//line 11 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/models/Country.hx"
		baseArr.push("icon");
		//line 11 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/models/Country.hx"
		baseArr.push("name");
		//line 11 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/models/Country.hx"
		super.__hx_getFields(baseArr);
	}
	
	
}


