// Generated by Haxe 4.0.5
package connect.models;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Event extends connect.models.Model
{
	public Event(haxe.lang.EmptyObject empty)
	{
		//line 13 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/models/Event.hx"
		super(haxe.lang.EmptyObject.EMPTY);
	}
	
	
	public Event()
	{
		//line 23 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/models/Event.hx"
		super(haxe.lang.EmptyObject.EMPTY);
		//line 23 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/models/Event.hx"
		connect.models.Event.__hx_ctor_connect_models_Event(this);
	}
	
	
	protected static void __hx_ctor_connect_models_Event(connect.models.Event __hx_this)
	{
		//line 23 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/models/Event.hx"
		connect.models.Model.__hx_ctor_connect_models_Model(__hx_this);
		//line 24 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/models/Event.hx"
		haxe.ds.StringMap<java.lang.String> _g = new haxe.ds.StringMap<java.lang.String>();
		//line 24 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/models/Event.hx"
		_g.set("at", "DateTime");
		//line 24 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/models/Event.hx"
		_g.set("by", "User");
		//line 24 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/models/Event.hx"
		__hx_this._setFieldClassNames(((haxe.ds.StringMap<java.lang.String>) (_g) ));
	}
	
	
	public connect.util.DateTime at;
	
	public connect.models.User by;
	
	@Override public java.lang.Object __hx_setField(java.lang.String field, java.lang.Object value, boolean handleProperties)
	{
		//line 13 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/models/Event.hx"
		{
			//line 13 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/models/Event.hx"
			boolean __temp_executeDef1 = true;
			//line 13 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/models/Event.hx"
			if (( field != null )) 
			{
				//line 13 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/models/Event.hx"
				switch (field.hashCode())
				{
					case 3159:
					{
						//line 13 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/models/Event.hx"
						if (field.equals("by")) 
						{
							//line 13 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/models/Event.hx"
							__temp_executeDef1 = false;
							//line 13 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/models/Event.hx"
							this.by = ((connect.models.User) (value) );
							//line 13 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/models/Event.hx"
							return value;
						}
						
						//line 13 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/models/Event.hx"
						break;
					}
					
					
					case 3123:
					{
						//line 13 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/models/Event.hx"
						if (field.equals("at")) 
						{
							//line 13 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/models/Event.hx"
							__temp_executeDef1 = false;
							//line 13 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/models/Event.hx"
							this.at = ((connect.util.DateTime) (value) );
							//line 13 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/models/Event.hx"
							return value;
						}
						
						//line 13 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/models/Event.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 13 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/models/Event.hx"
			if (__temp_executeDef1) 
			{
				//line 13 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/models/Event.hx"
				return super.__hx_setField(field, value, handleProperties);
			}
			else
			{
				//line 13 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/models/Event.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 13 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/models/Event.hx"
		{
			//line 13 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/models/Event.hx"
			boolean __temp_executeDef1 = true;
			//line 13 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/models/Event.hx"
			if (( field != null )) 
			{
				//line 13 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/models/Event.hx"
				switch (field.hashCode())
				{
					case 3159:
					{
						//line 13 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/models/Event.hx"
						if (field.equals("by")) 
						{
							//line 13 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/models/Event.hx"
							__temp_executeDef1 = false;
							//line 13 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/models/Event.hx"
							return this.by;
						}
						
						//line 13 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/models/Event.hx"
						break;
					}
					
					
					case 3123:
					{
						//line 13 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/models/Event.hx"
						if (field.equals("at")) 
						{
							//line 13 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/models/Event.hx"
							__temp_executeDef1 = false;
							//line 13 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/models/Event.hx"
							return this.at;
						}
						
						//line 13 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/models/Event.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 13 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/models/Event.hx"
			if (__temp_executeDef1) 
			{
				//line 13 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/models/Event.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 13 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/models/Event.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<java.lang.String> baseArr)
	{
		//line 13 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/models/Event.hx"
		baseArr.push("by");
		//line 13 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/models/Event.hx"
		baseArr.push("at");
		//line 13 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/models/Event.hx"
		super.__hx_getFields(baseArr);
	}
	
	
}


