// Generated by Haxe 4.0.5
package connect;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Flow_process_346__Fun extends haxe.lang.Function
{
	public Flow_process_346__Fun(connect.StepData stepData, connect.Flow _gthis)
	{
		//line 347 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/Flow.hx"
		super(2, 0);
		//line 347 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/Flow.hx"
		this.stepData = stepData;
		//line 347 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/Flow.hx"
		this._gthis = _gthis;
	}
	
	
	@Override public java.lang.Object __hx_invoke2_o(double __fn_float1, java.lang.Object __fn_dyn1, double __fn_float2, java.lang.Object __fn_dyn2)
	{
		//line 346 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/Flow.hx"
		java.lang.Object prev = ( (( __fn_dyn2 == haxe.lang.Runtime.undefined )) ? (((java.lang.Object) (__fn_float2) )) : (((java.lang.Object) (__fn_dyn2) )) );
		//line 346 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/Flow.hx"
		connect._Flow.Step step = ( (( __fn_dyn1 == haxe.lang.Runtime.undefined )) ? (((connect._Flow.Step) (((java.lang.Object) (__fn_float1) )) )) : (((connect._Flow.Step) (__fn_dyn1) )) );
		//line 347 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/Flow.hx"
		if (( ! (( prev == null )) )) 
		{
			//line 348 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/Flow.hx"
			return this._gthis.processStep(step, ( this.stepData.firstIndex + ((int) (haxe.lang.Runtime.getField_f(prev, "nextIndex", true)) ) ), haxe.lang.Runtime.toString(haxe.lang.Runtime.getField(prev, "lastRequestStr", true)), haxe.lang.Runtime.toString(haxe.lang.Runtime.getField(prev, "lastDataStr", true)));
		}
		else
		{
			//line 350 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/Flow.hx"
			return null;
		}
		
	}
	
	
	public connect.StepData stepData;
	
	public connect.Flow _gthis;
	
}


