// Generated by Haxe 4.0.5
package sys;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Http_requestUrl_494__Fun extends haxe.lang.Function
{
	public Http_requestUrl_494__Fun()
	{
		//line 495 "/home/travis/haxe/std/sys/Http.hx"
		super(1, 0);
	}
	
	
	public static sys.Http_requestUrl_494__Fun __hx_current;
	
	@Override public java.lang.Object __hx_invoke1_o(double __fn_float1, java.lang.Object __fn_dyn1)
	{
		//line 494 "/home/travis/haxe/std/sys/Http.hx"
		java.lang.String e = ( (( __fn_dyn1 == haxe.lang.Runtime.undefined )) ? (haxe.lang.Runtime.toString(__fn_float1)) : (haxe.lang.Runtime.toString(__fn_dyn1)) );
		//line 495 "/home/travis/haxe/std/sys/Http.hx"
		throw haxe.lang.HaxeException.wrap(e);
	}
	
	
}


