// Generated by Haxe 4.0.5
package sys;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Http extends haxe.http.HttpBase
{
	static
	{
		//line 46 "/home/travis/haxe/std/sys/Http.hx"
		sys.Http.PROXY = null;
	}
	
	public Http(haxe.lang.EmptyObject empty)
	{
		//line 31 "/home/travis/haxe/std/sys/Http.hx"
		super(((haxe.lang.EmptyObject) (haxe.lang.EmptyObject.EMPTY) ));
	}
	
	
	public Http(java.lang.String url)
	{
		//line 53 "/home/travis/haxe/std/sys/Http.hx"
		super(((haxe.lang.EmptyObject) (haxe.lang.EmptyObject.EMPTY) ));
		//line 53 "/home/travis/haxe/std/sys/Http.hx"
		sys.Http.__hx_ctor_sys_Http(this, url);
	}
	
	
	protected static void __hx_ctor_sys_Http(sys.Http __hx_this, java.lang.String url)
	{
		//line 49 "/home/travis/haxe/std/sys/Http.hx"
		__hx_this.cnxTimeout = ((double) (10) );
		//line 53 "/home/travis/haxe/std/sys/Http.hx"
		haxe.http.HttpBase.__hx_ctor_haxe_http_HttpBase(__hx_this, url);
	}
	
	
	public static java.lang.Object PROXY;
	
	public static java.lang.String requestUrl(java.lang.String url)
	{
		//line 489 "/home/travis/haxe/std/sys/Http.hx"
		sys.Http h = new sys.Http(haxe.lang.Runtime.toString(url));
		//line 490 "/home/travis/haxe/std/sys/Http.hx"
		java.lang.String[] r = new java.lang.String[]{null};
		//line 491 "/home/travis/haxe/std/sys/Http.hx"
		h.onData = new sys.Http_requestUrl_491__Fun(r);
		//line 494 "/home/travis/haxe/std/sys/Http.hx"
		h.onError = ( (( sys.Http_requestUrl_494__Fun.__hx_current != null )) ? (sys.Http_requestUrl_494__Fun.__hx_current) : (sys.Http_requestUrl_494__Fun.__hx_current = ((sys.Http_requestUrl_494__Fun) (new sys.Http_requestUrl_494__Fun()) )) );
		//line 497 "/home/travis/haxe/std/sys/Http.hx"
		h.request(false);
		//line 498 "/home/travis/haxe/std/sys/Http.hx"
		return r[0];
	}
	
	
	public boolean noShutdown;
	
	public double cnxTimeout;
	
	public haxe.ds.StringMap<java.lang.String> responseHeaders;
	
	public java.lang.Object chunk_size;
	
	public haxe.io.Bytes chunk_buf;
	
	public java.lang.Object file;
	
	@Override public void request(java.lang.Object post)
	{
		//line 57 "/home/travis/haxe/std/sys/Http.hx"
		haxe.io.BytesOutput output = new haxe.io.BytesOutput();
		//line 58 "/home/travis/haxe/std/sys/Http.hx"
		haxe.lang.Function old = this.onError;
		//line 59 "/home/travis/haxe/std/sys/Http.hx"
		boolean[] err = new boolean[]{false};
		//line 56 "/home/travis/haxe/std/sys/Http.hx"
		sys.Http _gthis = this;
		//line 60 "/home/travis/haxe/std/sys/Http.hx"
		this.onError = new sys.Http_request_60__Fun(output, old, err, _gthis);
		//line 67 "/home/travis/haxe/std/sys/Http.hx"
		post = ( ( haxe.lang.Runtime.toBool(((java.lang.Boolean) (post) )) || haxe.lang.Runtime.toBool(((java.lang.Boolean) (( this.postBytes != null )) )) ) || ( this.postData != null ) );
		//line 68 "/home/travis/haxe/std/sys/Http.hx"
		this.customRequest(haxe.lang.Runtime.toBool(((java.lang.Boolean) (post) )), output, null, null);
		//line 69 "/home/travis/haxe/std/sys/Http.hx"
		if ( ! (err[0]) ) 
		{
			//line 70 "/home/travis/haxe/std/sys/Http.hx"
			this.success(output.getBytes());
		}
		
	}
	
	
	public final void fileTransfert(java.lang.String argname, java.lang.String filename, haxe.io.Input file, int size, java.lang.String mimeType)
	{
		//line 77 "/home/travis/haxe/std/sys/Http.hx"
		if (( mimeType == null )) 
		{
			//line 77 "/home/travis/haxe/std/sys/Http.hx"
			mimeType = "application/octet-stream";
		}
		
		//line 77 "/home/travis/haxe/std/sys/Http.hx"
		this.fileTransfer(argname, filename, file, size, mimeType);
	}
	
	
	public void fileTransfer(java.lang.String argname, java.lang.String filename, haxe.io.Input file, int size, java.lang.String mimeType)
	{
		//line 81 "/home/travis/haxe/std/sys/Http.hx"
		if (( mimeType == null )) 
		{
			//line 81 "/home/travis/haxe/std/sys/Http.hx"
			mimeType = "application/octet-stream";
		}
		
		//line 81 "/home/travis/haxe/std/sys/Http.hx"
		this.file = new haxe.lang.DynamicObject(new java.lang.String[]{"filename", "io", "mimeType", "param"}, new java.lang.Object[]{filename, file, mimeType, argname}, new java.lang.String[]{"size"}, new double[]{((double) (((double) (size) )) )});
	}
	
	
	public void customRequest(boolean post, haxe.io.Output api, sys.net.Socket sock, java.lang.String method)
	{
		//line 91 "/home/travis/haxe/std/sys/Http.hx"
		this.responseAsString = null;
		//line 92 "/home/travis/haxe/std/sys/Http.hx"
		this.responseBytes = null;
		//line 93 "/home/travis/haxe/std/sys/Http.hx"
		haxe.root.EReg url_regexp = new haxe.root.EReg("^(https?://)?([a-zA-Z\\.0-9_-]+)(:[0-9]+)?(.*)$", "");
		//line 94 "/home/travis/haxe/std/sys/Http.hx"
		if ( ! (url_regexp.match(this.url)) ) 
		{
			//line 95 "/home/travis/haxe/std/sys/Http.hx"
			this.onError.__hx_invoke1_o(0.0, "Invalid URL");
			//line 96 "/home/travis/haxe/std/sys/Http.hx"
			return ;
		}
		
		//line 98 "/home/travis/haxe/std/sys/Http.hx"
		boolean secure = haxe.lang.Runtime.valEq(url_regexp.matched(1), "https://");
		//line 99 "/home/travis/haxe/std/sys/Http.hx"
		if (( sock == null )) 
		{
			//line 100 "/home/travis/haxe/std/sys/Http.hx"
			if (secure) 
			{
				//line 104 "/home/travis/haxe/std/sys/Http.hx"
				sock = new haxe.java.net.SslSocket();
			}
			else
			{
				//line 115 "/home/travis/haxe/std/sys/Http.hx"
				sock = new sys.net.Socket();
			}
			
			//line 117 "/home/travis/haxe/std/sys/Http.hx"
			sock.setTimeout(this.cnxTimeout);
		}
		
		//line 119 "/home/travis/haxe/std/sys/Http.hx"
		java.lang.String host = url_regexp.matched(2);
		//line 120 "/home/travis/haxe/std/sys/Http.hx"
		java.lang.String portString = url_regexp.matched(3);
		//line 121 "/home/travis/haxe/std/sys/Http.hx"
		java.lang.String request = url_regexp.matched(4);
		//line 125 "/home/travis/haxe/std/sys/Http.hx"
		if ( ! (haxe.lang.Runtime.valEq(haxe.lang.StringExt.charAt(request, 0), "/")) ) 
		{
			//line 126 "/home/travis/haxe/std/sys/Http.hx"
			request = ( "/" + request );
		}
		
		//line 128 "/home/travis/haxe/std/sys/Http.hx"
		java.lang.Object port = ( (( ( portString == null ) || haxe.lang.Runtime.valEq(portString, "") )) ? (( (secure) ? (443) : (80) )) : (haxe.root.Std.parseInt(haxe.lang.StringExt.substr(portString, 1, ( portString.length() - 1 )))) );
		//line 130 "/home/travis/haxe/std/sys/Http.hx"
		boolean multipart = ( ! (( this.file == null )) );
		//line 131 "/home/travis/haxe/std/sys/Http.hx"
		java.lang.String boundary = null;
		//line 132 "/home/travis/haxe/std/sys/Http.hx"
		java.lang.String uri = null;
		//line 133 "/home/travis/haxe/std/sys/Http.hx"
		if (multipart) 
		{
			//line 134 "/home/travis/haxe/std/sys/Http.hx"
			post = true;
			//line 135 "/home/travis/haxe/std/sys/Http.hx"
			boundary = ( ( ( haxe.root.Std.string(haxe.root.Std.random(1000)) + haxe.root.Std.string(haxe.root.Std.random(1000)) ) + haxe.root.Std.string(haxe.root.Std.random(1000)) ) + haxe.root.Std.string(haxe.root.Std.random(1000)) );
			//line 139 "/home/travis/haxe/std/sys/Http.hx"
			while (( boundary.length() < 38 ))
			{
				//line 140 "/home/travis/haxe/std/sys/Http.hx"
				boundary = ( "-" + boundary );
			}
			
			//line 141 "/home/travis/haxe/std/sys/Http.hx"
			haxe.root.StringBuf b = new haxe.root.StringBuf();
			//line 142 "/home/travis/haxe/std/sys/Http.hx"
			{
				//line 142 "/home/travis/haxe/std/sys/Http.hx"
				int _g = 0;
				//line 142 "/home/travis/haxe/std/sys/Http.hx"
				haxe.root.Array<java.lang.Object> _g1 = this.params;
				//line 142 "/home/travis/haxe/std/sys/Http.hx"
				while (( _g < _g1.length ))
				{
					//line 142 "/home/travis/haxe/std/sys/Http.hx"
					java.lang.Object p = _g1.__get(_g);
					//line 142 "/home/travis/haxe/std/sys/Http.hx"
					 ++ _g;
					//line 143 "/home/travis/haxe/std/sys/Http.hx"
					b.add(haxe.lang.Runtime.toString("--"));
					//line 143 "/home/travis/haxe/std/sys/Http.hx"
					java.lang.Object __temp_expr1 = ((java.lang.Object) (null) );
					//line 144 "/home/travis/haxe/std/sys/Http.hx"
					b.add(haxe.lang.Runtime.toString(boundary));
					//line 144 "/home/travis/haxe/std/sys/Http.hx"
					java.lang.Object __temp_expr2 = ((java.lang.Object) (null) );
					//line 145 "/home/travis/haxe/std/sys/Http.hx"
					b.add(haxe.lang.Runtime.toString("\r\n"));
					//line 145 "/home/travis/haxe/std/sys/Http.hx"
					java.lang.Object __temp_expr3 = ((java.lang.Object) (null) );
					//line 146 "/home/travis/haxe/std/sys/Http.hx"
					b.add(haxe.lang.Runtime.toString("Content-Disposition: form-data; name=\""));
					//line 146 "/home/travis/haxe/std/sys/Http.hx"
					java.lang.Object __temp_expr4 = ((java.lang.Object) (null) );
					//line 147 "/home/travis/haxe/std/sys/Http.hx"
					b.add(haxe.lang.Runtime.toString(haxe.lang.Runtime.getField(p, "name", true)));
					//line 147 "/home/travis/haxe/std/sys/Http.hx"
					java.lang.Object __temp_expr5 = ((java.lang.Object) (null) );
					//line 148 "/home/travis/haxe/std/sys/Http.hx"
					b.add(haxe.lang.Runtime.toString("\""));
					//line 148 "/home/travis/haxe/std/sys/Http.hx"
					java.lang.Object __temp_expr6 = ((java.lang.Object) (null) );
					//line 149 "/home/travis/haxe/std/sys/Http.hx"
					b.add(haxe.lang.Runtime.toString("\r\n"));
					//line 149 "/home/travis/haxe/std/sys/Http.hx"
					java.lang.Object __temp_expr7 = ((java.lang.Object) (null) );
					//line 150 "/home/travis/haxe/std/sys/Http.hx"
					b.add(haxe.lang.Runtime.toString("\r\n"));
					//line 150 "/home/travis/haxe/std/sys/Http.hx"
					java.lang.Object __temp_expr8 = ((java.lang.Object) (null) );
					//line 151 "/home/travis/haxe/std/sys/Http.hx"
					b.add(haxe.lang.Runtime.toString(haxe.lang.Runtime.getField(p, "value", true)));
					//line 151 "/home/travis/haxe/std/sys/Http.hx"
					java.lang.Object __temp_expr9 = ((java.lang.Object) (null) );
					//line 152 "/home/travis/haxe/std/sys/Http.hx"
					b.add(haxe.lang.Runtime.toString("\r\n"));
					//line 152 "/home/travis/haxe/std/sys/Http.hx"
					java.lang.Object __temp_expr10 = ((java.lang.Object) (null) );
				}
				
			}
			
			//line 154 "/home/travis/haxe/std/sys/Http.hx"
			b.add(haxe.lang.Runtime.toString("--"));
			//line 154 "/home/travis/haxe/std/sys/Http.hx"
			java.lang.Object __temp_expr11 = ((java.lang.Object) (null) );
			//line 155 "/home/travis/haxe/std/sys/Http.hx"
			b.add(haxe.lang.Runtime.toString(boundary));
			//line 155 "/home/travis/haxe/std/sys/Http.hx"
			java.lang.Object __temp_expr12 = ((java.lang.Object) (null) );
			//line 156 "/home/travis/haxe/std/sys/Http.hx"
			b.add(haxe.lang.Runtime.toString("\r\n"));
			//line 156 "/home/travis/haxe/std/sys/Http.hx"
			java.lang.Object __temp_expr13 = ((java.lang.Object) (null) );
			//line 157 "/home/travis/haxe/std/sys/Http.hx"
			b.add(haxe.lang.Runtime.toString("Content-Disposition: form-data; name=\""));
			//line 157 "/home/travis/haxe/std/sys/Http.hx"
			java.lang.Object __temp_expr14 = ((java.lang.Object) (null) );
			//line 158 "/home/travis/haxe/std/sys/Http.hx"
			b.add(haxe.lang.Runtime.toString(haxe.lang.Runtime.getField(this.file, "param", true)));
			//line 158 "/home/travis/haxe/std/sys/Http.hx"
			java.lang.Object __temp_expr15 = ((java.lang.Object) (null) );
			//line 159 "/home/travis/haxe/std/sys/Http.hx"
			b.add(haxe.lang.Runtime.toString("\"; filename=\""));
			//line 159 "/home/travis/haxe/std/sys/Http.hx"
			java.lang.Object __temp_expr16 = ((java.lang.Object) (null) );
			//line 160 "/home/travis/haxe/std/sys/Http.hx"
			b.add(haxe.lang.Runtime.toString(haxe.lang.Runtime.getField(this.file, "filename", true)));
			//line 160 "/home/travis/haxe/std/sys/Http.hx"
			java.lang.Object __temp_expr17 = ((java.lang.Object) (null) );
			//line 161 "/home/travis/haxe/std/sys/Http.hx"
			b.add(haxe.lang.Runtime.toString("\""));
			//line 161 "/home/travis/haxe/std/sys/Http.hx"
			java.lang.Object __temp_expr18 = ((java.lang.Object) (null) );
			//line 162 "/home/travis/haxe/std/sys/Http.hx"
			b.add(haxe.lang.Runtime.toString("\r\n"));
			//line 162 "/home/travis/haxe/std/sys/Http.hx"
			java.lang.Object __temp_expr19 = ((java.lang.Object) (null) );
			//line 163 "/home/travis/haxe/std/sys/Http.hx"
			b.add(haxe.lang.Runtime.toString(( ( ( "Content-Type: " + haxe.lang.Runtime.toString(haxe.lang.Runtime.getField(this.file, "mimeType", true)) ) + "\r\n" ) + "\r\n" )));
			//line 163 "/home/travis/haxe/std/sys/Http.hx"
			java.lang.Object __temp_expr20 = ((java.lang.Object) (null) );
			//line 164 "/home/travis/haxe/std/sys/Http.hx"
			uri = b.toString();
		}
		else
		{
			//line 166 "/home/travis/haxe/std/sys/Http.hx"
			int _g2 = 0;
			//line 166 "/home/travis/haxe/std/sys/Http.hx"
			haxe.root.Array<java.lang.Object> _g11 = this.params;
			//line 166 "/home/travis/haxe/std/sys/Http.hx"
			while (( _g2 < _g11.length ))
			{
				//line 166 "/home/travis/haxe/std/sys/Http.hx"
				java.lang.Object p1 = _g11.__get(_g2);
				//line 166 "/home/travis/haxe/std/sys/Http.hx"
				 ++ _g2;
				//line 167 "/home/travis/haxe/std/sys/Http.hx"
				if (( uri == null )) 
				{
					//line 168 "/home/travis/haxe/std/sys/Http.hx"
					uri = "";
				}
				else
				{
					//line 170 "/home/travis/haxe/std/sys/Http.hx"
					uri += "&";
				}
				
				//line 171 "/home/travis/haxe/std/sys/Http.hx"
				uri += ( ( haxe.root.StringTools.urlEncode(haxe.lang.Runtime.toString(haxe.lang.Runtime.getField(p1, "name", true))) + "=" ) + haxe.root.StringTools.urlEncode(( "" + haxe.lang.Runtime.toString(haxe.lang.Runtime.getField(p1, "value", true)) )) );
			}
			
		}
		
		//line 175 "/home/travis/haxe/std/sys/Http.hx"
		haxe.io.BytesOutput b1 = new haxe.io.BytesOutput();
		//line 176 "/home/travis/haxe/std/sys/Http.hx"
		if (( method != null )) 
		{
			//line 177 "/home/travis/haxe/std/sys/Http.hx"
			b1.writeString(method, null);
			//line 178 "/home/travis/haxe/std/sys/Http.hx"
			b1.writeString(" ", null);
		}
		else
		{
			//line 179 "/home/travis/haxe/std/sys/Http.hx"
			if (post) 
			{
				//line 180 "/home/travis/haxe/std/sys/Http.hx"
				b1.writeString("POST ", null);
			}
			else
			{
				//line 182 "/home/travis/haxe/std/sys/Http.hx"
				b1.writeString("GET ", null);
			}
			
		}
		
		//line 184 "/home/travis/haxe/std/sys/Http.hx"
		if (( ! (( sys.Http.PROXY == null )) )) 
		{
			//line 185 "/home/travis/haxe/std/sys/Http.hx"
			b1.writeString("http://", null);
			//line 186 "/home/travis/haxe/std/sys/Http.hx"
			b1.writeString(host, null);
			//line 187 "/home/travis/haxe/std/sys/Http.hx"
			if (( ! (haxe.lang.Runtime.eq(port, 80)) )) 
			{
				//line 188 "/home/travis/haxe/std/sys/Http.hx"
				b1.writeString(":", null);
				//line 189 "/home/travis/haxe/std/sys/Http.hx"
				b1.writeString(( haxe.lang.Runtime.toString("") + haxe.lang.Runtime.toString(port) ), null);
			}
			
		}
		
		//line 192 "/home/travis/haxe/std/sys/Http.hx"
		b1.writeString(request, null);
		//line 194 "/home/travis/haxe/std/sys/Http.hx"
		if ((  ! (post)  && ( uri != null ) )) 
		{
			//line 195 "/home/travis/haxe/std/sys/Http.hx"
			if (( haxe.lang.StringExt.indexOf(request, "?", 0) >= 0 )) 
			{
				//line 196 "/home/travis/haxe/std/sys/Http.hx"
				b1.writeString("&", null);
			}
			else
			{
				//line 198 "/home/travis/haxe/std/sys/Http.hx"
				b1.writeString("?", null);
			}
			
			//line 199 "/home/travis/haxe/std/sys/Http.hx"
			b1.writeString(uri, null);
		}
		
		//line 201 "/home/travis/haxe/std/sys/Http.hx"
		b1.writeString(( ( " HTTP/1.1\r\nHost: " + host ) + "\r\n" ), null);
		//line 202 "/home/travis/haxe/std/sys/Http.hx"
		if (( this.postData != null )) 
		{
			//line 203 "/home/travis/haxe/std/sys/Http.hx"
			this.postBytes = haxe.io.Bytes.ofString(this.postData, null);
			//line 204 "/home/travis/haxe/std/sys/Http.hx"
			this.postData = null;
		}
		
		//line 206 "/home/travis/haxe/std/sys/Http.hx"
		if (( this.postBytes != null )) 
		{
			//line 207 "/home/travis/haxe/std/sys/Http.hx"
			b1.writeString(( ( "Content-Length: " + this.postBytes.length ) + "\r\n" ), null);
		}
		else
		{
			//line 208 "/home/travis/haxe/std/sys/Http.hx"
			if (( post && ( uri != null ) )) 
			{
				//line 209 "/home/travis/haxe/std/sys/Http.hx"
				if (( multipart ||  ! (haxe.lang.Runtime.toBool(((java.lang.Boolean) (haxe.root.Lambda.exists(((java.lang.Object) (this.headers) ), ((haxe.lang.Function) (( (( sys.Http_customRequest_209__Fun.__hx_current != null )) ? (sys.Http_customRequest_209__Fun.__hx_current) : (sys.Http_customRequest_209__Fun.__hx_current = ((sys.Http_customRequest_209__Fun) (new sys.Http_customRequest_209__Fun()) )) )) ))) )))  )) 
				{
					//line 210 "/home/travis/haxe/std/sys/Http.hx"
					b1.writeString("Content-Type: ", null);
					//line 211 "/home/travis/haxe/std/sys/Http.hx"
					if (multipart) 
					{
						//line 212 "/home/travis/haxe/std/sys/Http.hx"
						b1.writeString("multipart/form-data", null);
						//line 213 "/home/travis/haxe/std/sys/Http.hx"
						b1.writeString("; boundary=", null);
						//line 214 "/home/travis/haxe/std/sys/Http.hx"
						b1.writeString(boundary, null);
					}
					else
					{
						//line 216 "/home/travis/haxe/std/sys/Http.hx"
						b1.writeString("application/x-www-form-urlencoded", null);
					}
					
					//line 217 "/home/travis/haxe/std/sys/Http.hx"
					b1.writeString("\r\n", null);
				}
				
				//line 219 "/home/travis/haxe/std/sys/Http.hx"
				if (multipart) 
				{
					//line 220 "/home/travis/haxe/std/sys/Http.hx"
					b1.writeString(( ( "Content-Length: " + (( ( ( uri.length() + ((int) (haxe.lang.Runtime.getField_f(this.file, "size", true)) ) ) + boundary.length() ) + 6 )) ) + "\r\n" ), null);
				}
				else
				{
					//line 222 "/home/travis/haxe/std/sys/Http.hx"
					b1.writeString(( ( "Content-Length: " + uri.length() ) + "\r\n" ), null);
				}
				
			}
			
		}
		
		//line 224 "/home/travis/haxe/std/sys/Http.hx"
		b1.writeString("Connection: close\r\n", null);
		//line 225 "/home/travis/haxe/std/sys/Http.hx"
		{
			//line 225 "/home/travis/haxe/std/sys/Http.hx"
			int _g3 = 0;
			//line 225 "/home/travis/haxe/std/sys/Http.hx"
			haxe.root.Array<java.lang.Object> _g12 = this.headers;
			//line 225 "/home/travis/haxe/std/sys/Http.hx"
			while (( _g3 < _g12.length ))
			{
				//line 225 "/home/travis/haxe/std/sys/Http.hx"
				java.lang.Object h1 = _g12.__get(_g3);
				//line 225 "/home/travis/haxe/std/sys/Http.hx"
				 ++ _g3;
				//line 226 "/home/travis/haxe/std/sys/Http.hx"
				b1.writeString(haxe.lang.Runtime.toString(haxe.lang.Runtime.getField(h1, "name", true)), null);
				//line 227 "/home/travis/haxe/std/sys/Http.hx"
				b1.writeString(": ", null);
				//line 228 "/home/travis/haxe/std/sys/Http.hx"
				b1.writeString(haxe.lang.Runtime.toString(haxe.lang.Runtime.getField(h1, "value", true)), null);
				//line 229 "/home/travis/haxe/std/sys/Http.hx"
				b1.writeString("\r\n", null);
			}
			
		}
		
		//line 231 "/home/travis/haxe/std/sys/Http.hx"
		b1.writeString("\r\n", null);
		//line 232 "/home/travis/haxe/std/sys/Http.hx"
		if (( this.postBytes != null )) 
		{
			//line 233 "/home/travis/haxe/std/sys/Http.hx"
			b1.writeFullBytes(this.postBytes, 0, this.postBytes.length);
		}
		else
		{
			//line 234 "/home/travis/haxe/std/sys/Http.hx"
			if (( post && ( uri != null ) )) 
			{
				//line 235 "/home/travis/haxe/std/sys/Http.hx"
				b1.writeString(uri, null);
			}
			
		}
		
		//line 236 "/home/travis/haxe/std/sys/Http.hx"
		try 
		{
			//line 237 "/home/travis/haxe/std/sys/Http.hx"
			if (( ! (( sys.Http.PROXY == null )) )) 
			{
				//line 238 "/home/travis/haxe/std/sys/Http.hx"
				sock.connect(new sys.net.Host(haxe.lang.Runtime.toString(haxe.lang.Runtime.getField(sys.Http.PROXY, "host", true))), ((int) (haxe.lang.Runtime.getField_f(sys.Http.PROXY, "port", true)) ));
			}
			else
			{
				//line 240 "/home/travis/haxe/std/sys/Http.hx"
				sock.connect(new sys.net.Host(haxe.lang.Runtime.toString(host)), ((int) (haxe.lang.Runtime.toInt(port)) ));
			}
			
			//line 241 "/home/travis/haxe/std/sys/Http.hx"
			if (multipart) 
			{
				//line 242 "/home/travis/haxe/std/sys/Http.hx"
				this.writeBody(b1, ((haxe.io.Input) (haxe.lang.Runtime.getField(this.file, "io", true)) ), ((int) (haxe.lang.Runtime.getField_f(this.file, "size", true)) ), boundary, sock);
			}
			else
			{
				//line 244 "/home/travis/haxe/std/sys/Http.hx"
				this.writeBody(b1, null, 0, null, sock);
			}
			
			//line 245 "/home/travis/haxe/std/sys/Http.hx"
			this.readHttpResponse(api, sock);
			//line 246 "/home/travis/haxe/std/sys/Http.hx"
			sock.close();
		}
		catch (java.lang.Throwable catchallException)
		{
			//line 236 "/home/travis/haxe/std/sys/Http.hx"
			haxe.lang.Exceptions.setException(catchallException);
			//line 247 "/home/travis/haxe/std/sys/Http.hx"
			{
				//line 247 "/home/travis/haxe/std/sys/Http.hx"
				java.lang.Object e = ( (haxe.root.Std.is(catchallException, haxe.lang.HaxeException.class)) ? (((haxe.lang.HaxeException) (catchallException) ).obj) : (catchallException) );
				//line 249 "/home/travis/haxe/std/sys/Http.hx"
				try 
				{
					//line 249 "/home/travis/haxe/std/sys/Http.hx"
					sock.close();
				}
				catch (java.lang.Throwable catchallException1)
				{
					//line 248 "/home/travis/haxe/std/sys/Http.hx"
					haxe.lang.Exceptions.setException(catchallException1);
					//line 250 "/home/travis/haxe/std/sys/Http.hx"
					java.lang.Object e1 = ( (haxe.root.Std.is(catchallException1, haxe.lang.HaxeException.class)) ? (((haxe.lang.HaxeException) (catchallException1) ).obj) : (catchallException1) );
				}
				
				
				//line 251 "/home/travis/haxe/std/sys/Http.hx"
				this.onError.__hx_invoke1_o(0.0, haxe.root.Std.string(e));
			}
			
		}
		
		
	}
	
	
	public void writeBody(haxe.io.BytesOutput body, haxe.io.Input fileInput, int fileSize, java.lang.String boundary, sys.net.Socket sock)
	{
		//line 255 "/home/travis/haxe/std/sys/Http.hx"
		try 
		{
			//line 256 "/home/travis/haxe/std/sys/Http.hx"
			if (( body != null )) 
			{
				//line 257 "/home/travis/haxe/std/sys/Http.hx"
				haxe.io.Bytes bytes = body.getBytes();
				//line 258 "/home/travis/haxe/std/sys/Http.hx"
				sock.output.writeFullBytes(bytes, 0, bytes.length);
			}
			
			//line 260 "/home/travis/haxe/std/sys/Http.hx"
			if (( boundary != null )) 
			{
				//line 261 "/home/travis/haxe/std/sys/Http.hx"
				int bufsize = 4096;
				//line 262 "/home/travis/haxe/std/sys/Http.hx"
				haxe.io.Bytes buf = haxe.io.Bytes.alloc(bufsize);
				//line 263 "/home/travis/haxe/std/sys/Http.hx"
				while (( fileSize > 0 ))
				{
					//line 264 "/home/travis/haxe/std/sys/Http.hx"
					int size = ( (( fileSize > bufsize )) ? (bufsize) : (fileSize) );
					//line 265 "/home/travis/haxe/std/sys/Http.hx"
					int len = 0;
					//line 267 "/home/travis/haxe/std/sys/Http.hx"
					try 
					{
						//line 267 "/home/travis/haxe/std/sys/Http.hx"
						len = fileInput.readBytes(buf, 0, size);
					}
					catch (java.lang.Throwable catchallException)
					{
						//line 266 "/home/travis/haxe/std/sys/Http.hx"
						haxe.lang.Exceptions.setException(catchallException);
						//line 269 "/home/travis/haxe/std/sys/Http.hx"
						java.lang.Object realException = ( (haxe.root.Std.is(catchallException, haxe.lang.HaxeException.class)) ? (((haxe.lang.HaxeException) (catchallException) ).obj) : (catchallException) );
						//line 269 "/home/travis/haxe/std/sys/Http.hx"
						if (( realException instanceof haxe.io.Eof )) 
						{
							//line 269 "/home/travis/haxe/std/sys/Http.hx"
							haxe.io.Eof e = ((haxe.io.Eof) (realException) );
							//line 269 "/home/travis/haxe/std/sys/Http.hx"
							break;
						}
						else
						{
							//line 269 "/home/travis/haxe/std/sys/Http.hx"
							throw catchallException;
						}
						
					}
					
					
					//line 270 "/home/travis/haxe/std/sys/Http.hx"
					sock.output.writeFullBytes(buf, 0, len);
					//line 271 "/home/travis/haxe/std/sys/Http.hx"
					fileSize -= len;
				}
				
				//line 273 "/home/travis/haxe/std/sys/Http.hx"
				sock.output.writeString("\r\n", null);
				//line 274 "/home/travis/haxe/std/sys/Http.hx"
				sock.output.writeString("--", null);
				//line 275 "/home/travis/haxe/std/sys/Http.hx"
				sock.output.writeString(boundary, null);
				//line 276 "/home/travis/haxe/std/sys/Http.hx"
				sock.output.writeString("--", null);
			}
			
		}
		catch (java.lang.Throwable typedException)
		{
			//line 255 "/home/travis/haxe/std/sys/Http.hx"
			throw haxe.lang.HaxeException.wrap(typedException);
		}
		
		
	}
	
	
	public void readHttpResponse(haxe.io.Output api, sys.net.Socket sock)
	{
		//line 280 "/home/travis/haxe/std/sys/Http.hx"
		try 
		{
			//line 282 "/home/travis/haxe/std/sys/Http.hx"
			haxe.io.BytesBuffer b = new haxe.io.BytesBuffer();
			//line 283 "/home/travis/haxe/std/sys/Http.hx"
			int k = 4;
			//line 284 "/home/travis/haxe/std/sys/Http.hx"
			haxe.io.Bytes s = haxe.io.Bytes.alloc(4);
			//line 285 "/home/travis/haxe/std/sys/Http.hx"
			sock.setTimeout(this.cnxTimeout);
			//line 286 "/home/travis/haxe/std/sys/Http.hx"
			label1:
			while (true)
			{
				//line 287 "/home/travis/haxe/std/sys/Http.hx"
				int p = sock.input.readBytes(s, 0, k);
				//line 288 "/home/travis/haxe/std/sys/Http.hx"
				while (( p != k ))
				{
					//line 289 "/home/travis/haxe/std/sys/Http.hx"
					p += sock.input.readBytes(s, p, ( k - p ));
				}
				
				//line 290 "/home/travis/haxe/std/sys/Http.hx"
				{
					//line 290 "/home/travis/haxe/std/sys/Http.hx"
					if (( ( k < 0 ) || ( k > s.length ) )) 
					{
						//line 290 "/home/travis/haxe/std/sys/Http.hx"
						throw haxe.lang.HaxeException.wrap(haxe.io.Error.OutsideBounds);
					}
					
					//line 290 "/home/travis/haxe/std/sys/Http.hx"
					b.b.write(((byte[]) (s.b) ), ((int) (0) ), ((int) (k) ));
				}
				
				//line 291 "/home/travis/haxe/std/sys/Http.hx"
				switch (k)
				{
					case 1:
					{
						//line 293 "/home/travis/haxe/std/sys/Http.hx"
						int c = ( s.b[0] & 255 );
						//line 294 "/home/travis/haxe/std/sys/Http.hx"
						if (( c == 10 )) 
						{
							//line 295 "/home/travis/haxe/std/sys/Http.hx"
							break label1;
						}
						
						//line 296 "/home/travis/haxe/std/sys/Http.hx"
						if (( c == 13 )) 
						{
							//line 297 "/home/travis/haxe/std/sys/Http.hx"
							k = 3;
						}
						else
						{
							//line 299 "/home/travis/haxe/std/sys/Http.hx"
							k = 4;
						}
						
						//line 292 "/home/travis/haxe/std/sys/Http.hx"
						break;
					}
					
					
					case 2:
					{
						//line 301 "/home/travis/haxe/std/sys/Http.hx"
						int c1 = ( s.b[1] & 255 );
						//line 302 "/home/travis/haxe/std/sys/Http.hx"
						if (( c1 == 10 )) 
						{
							//line 303 "/home/travis/haxe/std/sys/Http.hx"
							if (( (( s.b[0] & 255 )) == 13 )) 
							{
								//line 304 "/home/travis/haxe/std/sys/Http.hx"
								break label1;
							}
							
							//line 305 "/home/travis/haxe/std/sys/Http.hx"
							k = 4;
						}
						else
						{
							//line 306 "/home/travis/haxe/std/sys/Http.hx"
							if (( c1 == 13 )) 
							{
								//line 307 "/home/travis/haxe/std/sys/Http.hx"
								k = 3;
							}
							else
							{
								//line 309 "/home/travis/haxe/std/sys/Http.hx"
								k = 4;
							}
							
						}
						
						//line 300 "/home/travis/haxe/std/sys/Http.hx"
						break;
					}
					
					
					case 3:
					{
						//line 311 "/home/travis/haxe/std/sys/Http.hx"
						int c2 = ( s.b[2] & 255 );
						//line 312 "/home/travis/haxe/std/sys/Http.hx"
						if (( c2 == 10 )) 
						{
							//line 313 "/home/travis/haxe/std/sys/Http.hx"
							if (( (( s.b[1] & 255 )) != 13 )) 
							{
								//line 314 "/home/travis/haxe/std/sys/Http.hx"
								k = 4;
							}
							else
							{
								//line 315 "/home/travis/haxe/std/sys/Http.hx"
								if (( (( s.b[0] & 255 )) != 10 )) 
								{
									//line 316 "/home/travis/haxe/std/sys/Http.hx"
									k = 2;
								}
								else
								{
									//line 318 "/home/travis/haxe/std/sys/Http.hx"
									break label1;
								}
								
							}
							
						}
						else
						{
							//line 319 "/home/travis/haxe/std/sys/Http.hx"
							if (( c2 == 13 )) 
							{
								//line 320 "/home/travis/haxe/std/sys/Http.hx"
								if (( ( (( s.b[1] & 255 )) != 10 ) || ( (( s.b[0] & 255 )) != 13 ) )) 
								{
									//line 321 "/home/travis/haxe/std/sys/Http.hx"
									k = 1;
								}
								else
								{
									//line 323 "/home/travis/haxe/std/sys/Http.hx"
									k = 3;
								}
								
							}
							else
							{
								//line 325 "/home/travis/haxe/std/sys/Http.hx"
								k = 4;
							}
							
						}
						
						//line 310 "/home/travis/haxe/std/sys/Http.hx"
						break;
					}
					
					
					case 4:
					{
						//line 327 "/home/travis/haxe/std/sys/Http.hx"
						int c3 = ( s.b[3] & 255 );
						//line 328 "/home/travis/haxe/std/sys/Http.hx"
						if (( c3 == 10 )) 
						{
							//line 329 "/home/travis/haxe/std/sys/Http.hx"
							if (( (( s.b[2] & 255 )) != 13 )) 
							{
								//line 330 "/home/travis/haxe/std/sys/Http.hx"
								continue;
							}
							else
							{
								//line 331 "/home/travis/haxe/std/sys/Http.hx"
								if (( ( (( s.b[1] & 255 )) != 10 ) || ( (( s.b[0] & 255 )) != 13 ) )) 
								{
									//line 332 "/home/travis/haxe/std/sys/Http.hx"
									k = 2;
								}
								else
								{
									//line 334 "/home/travis/haxe/std/sys/Http.hx"
									break label1;
								}
								
							}
							
						}
						else
						{
							//line 335 "/home/travis/haxe/std/sys/Http.hx"
							if (( c3 == 13 )) 
							{
								//line 336 "/home/travis/haxe/std/sys/Http.hx"
								if (( ( (( s.b[2] & 255 )) != 10 ) || ( (( s.b[1] & 255 )) != 13 ) )) 
								{
									//line 337 "/home/travis/haxe/std/sys/Http.hx"
									k = 3;
								}
								else
								{
									//line 339 "/home/travis/haxe/std/sys/Http.hx"
									k = 1;
								}
								
							}
							
						}
						
						//line 326 "/home/travis/haxe/std/sys/Http.hx"
						break;
					}
					
					
				}
				
			}
			;
			//line 346 "/home/travis/haxe/std/sys/Http.hx"
			haxe.root.Array<java.lang.String> headers = haxe.lang.StringExt.split(b.getBytes().toString(), "\r\n");
			//line 348 "/home/travis/haxe/std/sys/Http.hx"
			java.lang.String response = haxe.lang.Runtime.toString(headers.shift());
			//line 349 "/home/travis/haxe/std/sys/Http.hx"
			haxe.root.Array<java.lang.String> rp = haxe.lang.StringExt.split(response, " ");
			//line 350 "/home/travis/haxe/std/sys/Http.hx"
			java.lang.Object status = haxe.root.Std.parseInt(rp.__get(1));
			//line 351 "/home/travis/haxe/std/sys/Http.hx"
			if (( haxe.lang.Runtime.eq(status, 0) || haxe.lang.Runtime.eq(status, null) )) 
			{
				//line 352 "/home/travis/haxe/std/sys/Http.hx"
				throw haxe.lang.HaxeException.wrap("Response status error");
			}
			
			//line 355 "/home/travis/haxe/std/sys/Http.hx"
			java.lang.String __temp_expr1 = haxe.lang.Runtime.toString(headers.pop());
			//line 356 "/home/travis/haxe/std/sys/Http.hx"
			java.lang.String __temp_expr2 = haxe.lang.Runtime.toString(headers.pop());
			//line 357 "/home/travis/haxe/std/sys/Http.hx"
			this.responseHeaders = ((haxe.ds.StringMap<java.lang.String>) (new haxe.ds.StringMap<java.lang.String>()) );
			//line 358 "/home/travis/haxe/std/sys/Http.hx"
			java.lang.Object size = null;
			//line 359 "/home/travis/haxe/std/sys/Http.hx"
			boolean chunked = false;
			//line 360 "/home/travis/haxe/std/sys/Http.hx"
			{
				//line 360 "/home/travis/haxe/std/sys/Http.hx"
				int _g = 0;
				//line 360 "/home/travis/haxe/std/sys/Http.hx"
				while (( _g < headers.length ))
				{
					//line 360 "/home/travis/haxe/std/sys/Http.hx"
					java.lang.String hline = headers.__get(_g);
					//line 360 "/home/travis/haxe/std/sys/Http.hx"
					 ++ _g;
					//line 361 "/home/travis/haxe/std/sys/Http.hx"
					haxe.root.Array<java.lang.String> a = haxe.lang.StringExt.split(hline, ": ");
					//line 362 "/home/travis/haxe/std/sys/Http.hx"
					java.lang.String hname = haxe.lang.Runtime.toString(a.shift());
					//line 363 "/home/travis/haxe/std/sys/Http.hx"
					java.lang.String hval = ( (( a.length == 1 )) ? (a.__get(0)) : (a.join(": ")) );
					//line 364 "/home/travis/haxe/std/sys/Http.hx"
					hval = haxe.root.StringTools.ltrim(haxe.root.StringTools.rtrim(hval));
					//line 365 "/home/travis/haxe/std/sys/Http.hx"
					((haxe.ds.StringMap<java.lang.String>) (((haxe.IMap<java.lang.String, java.lang.String>) (this.responseHeaders) )) ).set(hname, hval);
					//line 366 "/home/travis/haxe/std/sys/Http.hx"
					{
						//line 366 "/home/travis/haxe/std/sys/Http.hx"
						java.lang.String __temp_svar3 = (hname.toLowerCase());
						//line 366 "/home/travis/haxe/std/sys/Http.hx"
						if (( __temp_svar3 != null )) 
						{
							//line 366 "/home/travis/haxe/std/sys/Http.hx"
							switch (__temp_svar3.hashCode())
							{
								case -1132779846:
								{
									//line 368 "/home/travis/haxe/std/sys/Http.hx"
									if (__temp_svar3.equals("content-length")) 
									{
										//line 368 "/home/travis/haxe/std/sys/Http.hx"
										size = haxe.root.Std.parseInt(hval);
									}
									
									//line 368 "/home/travis/haxe/std/sys/Http.hx"
									break;
								}
								
								
								case 1274458357:
								{
									//line 370 "/home/travis/haxe/std/sys/Http.hx"
									if (__temp_svar3.equals("transfer-encoding")) 
									{
										//line 370 "/home/travis/haxe/std/sys/Http.hx"
										chunked = haxe.lang.Runtime.valEq(hval.toLowerCase(), "chunked");
									}
									
									//line 370 "/home/travis/haxe/std/sys/Http.hx"
									break;
								}
								
								
							}
							
						}
						
					}
					
				}
				
			}
			
			//line 374 "/home/travis/haxe/std/sys/Http.hx"
			this.onStatus.__hx_invoke1_o(0.0, status);
			//line 376 "/home/travis/haxe/std/sys/Http.hx"
			haxe.root.EReg chunk_re = new haxe.root.EReg("^([0-9A-Fa-f]+)[ ]*\r\n", "m");
			//line 377 "/home/travis/haxe/std/sys/Http.hx"
			this.chunk_size = null;
			//line 378 "/home/travis/haxe/std/sys/Http.hx"
			this.chunk_buf = null;
			//line 380 "/home/travis/haxe/std/sys/Http.hx"
			int bufsize = 1024;
			//line 381 "/home/travis/haxe/std/sys/Http.hx"
			haxe.io.Bytes buf = haxe.io.Bytes.alloc(bufsize);
			//line 382 "/home/travis/haxe/std/sys/Http.hx"
			if (chunked) 
			{
				//line 384 "/home/travis/haxe/std/sys/Http.hx"
				try 
				{
					//line 384 "/home/travis/haxe/std/sys/Http.hx"
					while (true)
					{
						//line 385 "/home/travis/haxe/std/sys/Http.hx"
						int len = sock.input.readBytes(buf, 0, bufsize);
						//line 386 "/home/travis/haxe/std/sys/Http.hx"
						if ( ! (this.readChunk(chunk_re, api, buf, len)) ) 
						{
							//line 387 "/home/travis/haxe/std/sys/Http.hx"
							break;
						}
						
					}
					
				}
				catch (java.lang.Throwable catchallException)
				{
					//line 383 "/home/travis/haxe/std/sys/Http.hx"
					haxe.lang.Exceptions.setException(catchallException);
					//line 390 "/home/travis/haxe/std/sys/Http.hx"
					java.lang.Object realException = ( (haxe.root.Std.is(catchallException, haxe.lang.HaxeException.class)) ? (((haxe.lang.HaxeException) (catchallException) ).obj) : (catchallException) );
					//line 390 "/home/travis/haxe/std/sys/Http.hx"
					if (( realException instanceof haxe.io.Eof )) 
					{
						//line 390 "/home/travis/haxe/std/sys/Http.hx"
						haxe.io.Eof e = ((haxe.io.Eof) (realException) );
						//line 390 "/home/travis/haxe/std/sys/Http.hx"
						throw haxe.lang.HaxeException.wrap("Transfer aborted");
					}
					else
					{
						//line 390 "/home/travis/haxe/std/sys/Http.hx"
						throw catchallException;
					}
					
				}
				
				
			}
			else
			{
				//line 392 "/home/travis/haxe/std/sys/Http.hx"
				if (haxe.lang.Runtime.eq(size, null)) 
				{
					//line 393 "/home/travis/haxe/std/sys/Http.hx"
					if ( ! (this.noShutdown) ) 
					{
						//line 394 "/home/travis/haxe/std/sys/Http.hx"
						sock.shutdown(false, true);
					}
					
					//line 396 "/home/travis/haxe/std/sys/Http.hx"
					try 
					{
						//line 396 "/home/travis/haxe/std/sys/Http.hx"
						while (true)
						{
							//line 397 "/home/travis/haxe/std/sys/Http.hx"
							int len1 = sock.input.readBytes(buf, 0, bufsize);
							//line 398 "/home/travis/haxe/std/sys/Http.hx"
							if (( len1 == 0 )) 
							{
								//line 399 "/home/travis/haxe/std/sys/Http.hx"
								break;
							}
							
							//line 400 "/home/travis/haxe/std/sys/Http.hx"
							api.writeBytes(buf, 0, len1);
						}
						
					}
					catch (java.lang.Throwable catchallException1)
					{
						//line 395 "/home/travis/haxe/std/sys/Http.hx"
						haxe.lang.Exceptions.setException(catchallException1);
						//line 402 "/home/travis/haxe/std/sys/Http.hx"
						java.lang.Object realException1 = ( (haxe.root.Std.is(catchallException1, haxe.lang.HaxeException.class)) ? (((haxe.lang.HaxeException) (catchallException1) ).obj) : (catchallException1) );
						//line 402 "/home/travis/haxe/std/sys/Http.hx"
						if (( realException1 instanceof haxe.io.Eof )) 
						{
							//line 402 "/home/travis/haxe/std/sys/Http.hx"
							haxe.io.Eof e1 = ((haxe.io.Eof) (realException1) );
						}
						else
						{
							//line 402 "/home/travis/haxe/std/sys/Http.hx"
							throw catchallException1;
						}
						
					}
					
					
				}
				else
				{
					//line 404 "/home/travis/haxe/std/sys/Http.hx"
					api.prepare(((int) (haxe.lang.Runtime.toInt(size)) ));
					//line 406 "/home/travis/haxe/std/sys/Http.hx"
					try 
					{
						//line 406 "/home/travis/haxe/std/sys/Http.hx"
						while (( ((int) (haxe.lang.Runtime.toInt(size)) ) > 0 ))
						{
							//line 407 "/home/travis/haxe/std/sys/Http.hx"
							int len2 = sock.input.readBytes(buf, 0, ( (( ((int) (haxe.lang.Runtime.toInt(size)) ) > bufsize )) ? (bufsize) : (((int) (haxe.lang.Runtime.toInt(size)) )) ));
							//line 408 "/home/travis/haxe/std/sys/Http.hx"
							api.writeBytes(buf, 0, len2);
							//line 409 "/home/travis/haxe/std/sys/Http.hx"
							size = ( ((int) (haxe.lang.Runtime.toInt(size)) ) - ((int) (len2) ) );
						}
						
					}
					catch (java.lang.Throwable catchallException2)
					{
						//line 405 "/home/travis/haxe/std/sys/Http.hx"
						haxe.lang.Exceptions.setException(catchallException2);
						//line 412 "/home/travis/haxe/std/sys/Http.hx"
						java.lang.Object realException2 = ( (haxe.root.Std.is(catchallException2, haxe.lang.HaxeException.class)) ? (((haxe.lang.HaxeException) (catchallException2) ).obj) : (catchallException2) );
						//line 412 "/home/travis/haxe/std/sys/Http.hx"
						if (( realException2 instanceof haxe.io.Eof )) 
						{
							//line 412 "/home/travis/haxe/std/sys/Http.hx"
							haxe.io.Eof e2 = ((haxe.io.Eof) (realException2) );
							//line 412 "/home/travis/haxe/std/sys/Http.hx"
							throw haxe.lang.HaxeException.wrap("Transfer aborted");
						}
						else
						{
							//line 412 "/home/travis/haxe/std/sys/Http.hx"
							throw catchallException2;
						}
						
					}
					
					
				}
				
			}
			
			//line 415 "/home/travis/haxe/std/sys/Http.hx"
			if (( chunked && (( ( ! (haxe.lang.Runtime.eq(this.chunk_size, null)) ) || ( this.chunk_buf != null ) )) )) 
			{
				//line 416 "/home/travis/haxe/std/sys/Http.hx"
				throw haxe.lang.HaxeException.wrap("Invalid chunk");
			}
			
			//line 417 "/home/travis/haxe/std/sys/Http.hx"
			if (( ( ((int) (haxe.lang.Runtime.toInt(status)) ) < 200 ) || ( ((int) (haxe.lang.Runtime.toInt(status)) ) >= 400 ) )) 
			{
				//line 418 "/home/travis/haxe/std/sys/Http.hx"
				throw haxe.lang.HaxeException.wrap(( haxe.lang.Runtime.toString("Http Error #") + haxe.lang.Runtime.toString(status) ));
			}
			
			//line 419 "/home/travis/haxe/std/sys/Http.hx"
			api.close();
		}
		catch (java.lang.Throwable typedException)
		{
			//line 280 "/home/travis/haxe/std/sys/Http.hx"
			throw haxe.lang.HaxeException.wrap(typedException);
		}
		
		
	}
	
	
	public boolean readChunk(haxe.root.EReg chunk_re, haxe.io.Output api, haxe.io.Bytes buf, int len)
	{
		//line 422 "/home/travis/haxe/std/sys/Http.hx"
		try 
		{
			//line 423 "/home/travis/haxe/std/sys/Http.hx"
			if (haxe.lang.Runtime.eq(this.chunk_size, null)) 
			{
				//line 424 "/home/travis/haxe/std/sys/Http.hx"
				if (( this.chunk_buf != null )) 
				{
					//line 425 "/home/travis/haxe/std/sys/Http.hx"
					haxe.io.BytesBuffer b = new haxe.io.BytesBuffer();
					//line 426 "/home/travis/haxe/std/sys/Http.hx"
					{
						//line 426 "/home/travis/haxe/std/sys/Http.hx"
						haxe.io.Bytes src = this.chunk_buf;
						//line 426 "/home/travis/haxe/std/sys/Http.hx"
						b.b.write(((byte[]) (src.b) ), ((int) (0) ), ((int) (src.length) ));
					}
					
					//line 427 "/home/travis/haxe/std/sys/Http.hx"
					{
						//line 427 "/home/travis/haxe/std/sys/Http.hx"
						if (( ( len < 0 ) || ( len > buf.length ) )) 
						{
							//line 427 "/home/travis/haxe/std/sys/Http.hx"
							throw haxe.lang.HaxeException.wrap(haxe.io.Error.OutsideBounds);
						}
						
						//line 427 "/home/travis/haxe/std/sys/Http.hx"
						b.b.write(((byte[]) (buf.b) ), ((int) (0) ), ((int) (len) ));
					}
					
					//line 428 "/home/travis/haxe/std/sys/Http.hx"
					buf = b.getBytes();
					//line 429 "/home/travis/haxe/std/sys/Http.hx"
					len += this.chunk_buf.length;
					//line 430 "/home/travis/haxe/std/sys/Http.hx"
					this.chunk_buf = null;
				}
				
				//line 435 "/home/travis/haxe/std/sys/Http.hx"
				if (chunk_re.match(buf.toString())) 
				{
					//line 437 "/home/travis/haxe/std/sys/Http.hx"
					java.lang.Object p = chunk_re.matchedPos();
					//line 438 "/home/travis/haxe/std/sys/Http.hx"
					if (( ((int) (haxe.lang.Runtime.getField_f(p, "len", true)) ) <= len )) 
					{
						//line 439 "/home/travis/haxe/std/sys/Http.hx"
						java.lang.String cstr = chunk_re.matched(1);
						//line 440 "/home/travis/haxe/std/sys/Http.hx"
						this.chunk_size = haxe.root.Std.parseInt(( "0x" + cstr ));
						//line 441 "/home/travis/haxe/std/sys/Http.hx"
						if (haxe.lang.Runtime.eq(this.chunk_size, 0)) 
						{
							//line 442 "/home/travis/haxe/std/sys/Http.hx"
							this.chunk_size = null;
							//line 443 "/home/travis/haxe/std/sys/Http.hx"
							this.chunk_buf = null;
							//line 444 "/home/travis/haxe/std/sys/Http.hx"
							return false;
						}
						
						//line 446 "/home/travis/haxe/std/sys/Http.hx"
						len = ( ((int) (len) ) - ((int) (haxe.lang.Runtime.getField_f(p, "len", true)) ) );
						//line 447 "/home/travis/haxe/std/sys/Http.hx"
						return this.readChunk(chunk_re, api, buf.sub(((int) (haxe.lang.Runtime.getField_f(p, "len", true)) ), len), len);
					}
					
				}
				
				//line 451 "/home/travis/haxe/std/sys/Http.hx"
				if (( len > 10 )) 
				{
					//line 452 "/home/travis/haxe/std/sys/Http.hx"
					this.onError.__hx_invoke1_o(0.0, "Invalid chunk");
					//line 453 "/home/travis/haxe/std/sys/Http.hx"
					return false;
				}
				
				//line 455 "/home/travis/haxe/std/sys/Http.hx"
				this.chunk_buf = buf.sub(0, len);
				//line 456 "/home/travis/haxe/std/sys/Http.hx"
				return true;
			}
			
			//line 459 "/home/travis/haxe/std/sys/Http.hx"
			if (( ((int) (haxe.lang.Runtime.toInt(this.chunk_size)) ) > len )) 
			{
				//line 460 "/home/travis/haxe/std/sys/Http.hx"
				{
					//line 460 "/home/travis/haxe/std/sys/Http.hx"
					sys.Http __temp_dynop1 = this;
					//line 460 "/home/travis/haxe/std/sys/Http.hx"
					__temp_dynop1.chunk_size = ( ((int) (haxe.lang.Runtime.toInt(__temp_dynop1.chunk_size)) ) - ((int) (len) ) );
				}
				
				//line 461 "/home/travis/haxe/std/sys/Http.hx"
				api.writeBytes(buf, 0, len);
				//line 462 "/home/travis/haxe/std/sys/Http.hx"
				return true;
			}
			
			//line 464 "/home/travis/haxe/std/sys/Http.hx"
			int end = ((int) (haxe.lang.Runtime.toInt(haxe.lang.Runtime.plus(this.chunk_size, 2))) );
			//line 465 "/home/travis/haxe/std/sys/Http.hx"
			if (( len >= end )) 
			{
				//line 466 "/home/travis/haxe/std/sys/Http.hx"
				if (( ((int) (haxe.lang.Runtime.toInt(this.chunk_size)) ) > 0 )) 
				{
					//line 467 "/home/travis/haxe/std/sys/Http.hx"
					api.writeBytes(buf, 0, ((int) (haxe.lang.Runtime.toInt(this.chunk_size)) ));
				}
				
				//line 468 "/home/travis/haxe/std/sys/Http.hx"
				len -= end;
				//line 469 "/home/travis/haxe/std/sys/Http.hx"
				this.chunk_size = null;
				//line 470 "/home/travis/haxe/std/sys/Http.hx"
				if (( len == 0 )) 
				{
					//line 471 "/home/travis/haxe/std/sys/Http.hx"
					return true;
				}
				
				//line 472 "/home/travis/haxe/std/sys/Http.hx"
				return this.readChunk(chunk_re, api, buf.sub(end, len), len);
			}
			
			//line 474 "/home/travis/haxe/std/sys/Http.hx"
			if (( ((int) (haxe.lang.Runtime.toInt(this.chunk_size)) ) > 0 )) 
			{
				//line 475 "/home/travis/haxe/std/sys/Http.hx"
				api.writeBytes(buf, 0, ((int) (haxe.lang.Runtime.toInt(this.chunk_size)) ));
			}
			
			//line 476 "/home/travis/haxe/std/sys/Http.hx"
			{
				//line 476 "/home/travis/haxe/std/sys/Http.hx"
				sys.Http __temp_dynop2 = this;
				//line 476 "/home/travis/haxe/std/sys/Http.hx"
				__temp_dynop2.chunk_size = ( ((int) (haxe.lang.Runtime.toInt(__temp_dynop2.chunk_size)) ) - ((int) (len) ) );
			}
			
			//line 477 "/home/travis/haxe/std/sys/Http.hx"
			return true;
		}
		catch (java.lang.Throwable typedException)
		{
			//line 422 "/home/travis/haxe/std/sys/Http.hx"
			throw haxe.lang.HaxeException.wrap(typedException);
		}
		
		
	}
	
	
	@Override public double __hx_setField_f(java.lang.String field, double value, boolean handleProperties)
	{
		//line 31 "/home/travis/haxe/std/sys/Http.hx"
		{
			//line 31 "/home/travis/haxe/std/sys/Http.hx"
			boolean __temp_executeDef1 = true;
			//line 31 "/home/travis/haxe/std/sys/Http.hx"
			if (( field != null )) 
			{
				//line 31 "/home/travis/haxe/std/sys/Http.hx"
				switch (field.hashCode())
				{
					case 3143036:
					{
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						if (field.equals("file")) 
						{
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							__temp_executeDef1 = false;
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							this.file = ((java.lang.Object) (value) );
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							return value;
						}
						
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						break;
					}
					
					
					case -196911308:
					{
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						if (field.equals("cnxTimeout")) 
						{
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							__temp_executeDef1 = false;
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							this.cnxTimeout = ((double) (value) );
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							return value;
						}
						
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						break;
					}
					
					
					case -1525550445:
					{
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						if (field.equals("chunk_size")) 
						{
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							__temp_executeDef1 = false;
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							this.chunk_size = ((java.lang.Object) (value) );
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							return value;
						}
						
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 31 "/home/travis/haxe/std/sys/Http.hx"
			if (__temp_executeDef1) 
			{
				//line 31 "/home/travis/haxe/std/sys/Http.hx"
				return super.__hx_setField_f(field, value, handleProperties);
			}
			else
			{
				//line 31 "/home/travis/haxe/std/sys/Http.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_setField(java.lang.String field, java.lang.Object value, boolean handleProperties)
	{
		//line 31 "/home/travis/haxe/std/sys/Http.hx"
		{
			//line 31 "/home/travis/haxe/std/sys/Http.hx"
			boolean __temp_executeDef1 = true;
			//line 31 "/home/travis/haxe/std/sys/Http.hx"
			if (( field != null )) 
			{
				//line 31 "/home/travis/haxe/std/sys/Http.hx"
				switch (field.hashCode())
				{
					case 3143036:
					{
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						if (field.equals("file")) 
						{
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							__temp_executeDef1 = false;
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							this.file = ((java.lang.Object) (value) );
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							return value;
						}
						
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						break;
					}
					
					
					case 989669175:
					{
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						if (field.equals("noShutdown")) 
						{
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							__temp_executeDef1 = false;
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							this.noShutdown = haxe.lang.Runtime.toBool(((java.lang.Boolean) (value) ));
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							return value;
						}
						
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						break;
					}
					
					
					case 2028982689:
					{
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						if (field.equals("chunk_buf")) 
						{
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							__temp_executeDef1 = false;
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							this.chunk_buf = ((haxe.io.Bytes) (value) );
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							return value;
						}
						
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						break;
					}
					
					
					case -196911308:
					{
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						if (field.equals("cnxTimeout")) 
						{
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							__temp_executeDef1 = false;
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							this.cnxTimeout = ((double) (haxe.lang.Runtime.toDouble(value)) );
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							return value;
						}
						
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						break;
					}
					
					
					case -1525550445:
					{
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						if (field.equals("chunk_size")) 
						{
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							__temp_executeDef1 = false;
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							this.chunk_size = ((java.lang.Object) (value) );
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							return value;
						}
						
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						break;
					}
					
					
					case 1387714565:
					{
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						if (field.equals("responseHeaders")) 
						{
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							__temp_executeDef1 = false;
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							this.responseHeaders = ((haxe.ds.StringMap<java.lang.String>) (value) );
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							return value;
						}
						
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 31 "/home/travis/haxe/std/sys/Http.hx"
			if (__temp_executeDef1) 
			{
				//line 31 "/home/travis/haxe/std/sys/Http.hx"
				return super.__hx_setField(field, value, handleProperties);
			}
			else
			{
				//line 31 "/home/travis/haxe/std/sys/Http.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 31 "/home/travis/haxe/std/sys/Http.hx"
		{
			//line 31 "/home/travis/haxe/std/sys/Http.hx"
			boolean __temp_executeDef1 = true;
			//line 31 "/home/travis/haxe/std/sys/Http.hx"
			if (( field != null )) 
			{
				//line 31 "/home/travis/haxe/std/sys/Http.hx"
				switch (field.hashCode())
				{
					case -1139644809:
					{
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						if (field.equals("readChunk")) 
						{
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							__temp_executeDef1 = false;
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "readChunk")) );
						}
						
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						break;
					}
					
					
					case 989669175:
					{
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						if (field.equals("noShutdown")) 
						{
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							__temp_executeDef1 = false;
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							return this.noShutdown;
						}
						
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						break;
					}
					
					
					case -954305121:
					{
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						if (field.equals("readHttpResponse")) 
						{
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							__temp_executeDef1 = false;
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "readHttpResponse")) );
						}
						
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						break;
					}
					
					
					case -196911308:
					{
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						if (field.equals("cnxTimeout")) 
						{
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							__temp_executeDef1 = false;
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							return this.cnxTimeout;
						}
						
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						break;
					}
					
					
					case -1406861791:
					{
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						if (field.equals("writeBody")) 
						{
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							__temp_executeDef1 = false;
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "writeBody")) );
						}
						
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						break;
					}
					
					
					case 1387714565:
					{
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						if (field.equals("responseHeaders")) 
						{
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							__temp_executeDef1 = false;
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							return this.responseHeaders;
						}
						
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						break;
					}
					
					
					case 2113105374:
					{
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						if (field.equals("customRequest")) 
						{
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							__temp_executeDef1 = false;
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "customRequest")) );
						}
						
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						break;
					}
					
					
					case -1525550445:
					{
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						if (field.equals("chunk_size")) 
						{
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							__temp_executeDef1 = false;
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							return this.chunk_size;
						}
						
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						break;
					}
					
					
					case 12834183:
					{
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						if (field.equals("fileTransfer")) 
						{
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							__temp_executeDef1 = false;
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "fileTransfer")) );
						}
						
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						break;
					}
					
					
					case 2028982689:
					{
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						if (field.equals("chunk_buf")) 
						{
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							__temp_executeDef1 = false;
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							return this.chunk_buf;
						}
						
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						break;
					}
					
					
					case 397859789:
					{
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						if (field.equals("fileTransfert")) 
						{
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							__temp_executeDef1 = false;
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "fileTransfert")) );
						}
						
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						break;
					}
					
					
					case 3143036:
					{
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						if (field.equals("file")) 
						{
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							__temp_executeDef1 = false;
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							return this.file;
						}
						
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						break;
					}
					
					
					case 1095692943:
					{
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						if (field.equals("request")) 
						{
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							__temp_executeDef1 = false;
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "request")) );
						}
						
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 31 "/home/travis/haxe/std/sys/Http.hx"
			if (__temp_executeDef1) 
			{
				//line 31 "/home/travis/haxe/std/sys/Http.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 31 "/home/travis/haxe/std/sys/Http.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public double __hx_getField_f(java.lang.String field, boolean throwErrors, boolean handleProperties)
	{
		//line 31 "/home/travis/haxe/std/sys/Http.hx"
		{
			//line 31 "/home/travis/haxe/std/sys/Http.hx"
			boolean __temp_executeDef1 = true;
			//line 31 "/home/travis/haxe/std/sys/Http.hx"
			if (( field != null )) 
			{
				//line 31 "/home/travis/haxe/std/sys/Http.hx"
				switch (field.hashCode())
				{
					case 3143036:
					{
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						if (field.equals("file")) 
						{
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							__temp_executeDef1 = false;
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							return ((double) (haxe.lang.Runtime.toDouble(this.file)) );
						}
						
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						break;
					}
					
					
					case -196911308:
					{
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						if (field.equals("cnxTimeout")) 
						{
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							__temp_executeDef1 = false;
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							return this.cnxTimeout;
						}
						
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						break;
					}
					
					
					case -1525550445:
					{
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						if (field.equals("chunk_size")) 
						{
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							__temp_executeDef1 = false;
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							return ((double) (haxe.lang.Runtime.toDouble(this.chunk_size)) );
						}
						
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 31 "/home/travis/haxe/std/sys/Http.hx"
			if (__temp_executeDef1) 
			{
				//line 31 "/home/travis/haxe/std/sys/Http.hx"
				return super.__hx_getField_f(field, throwErrors, handleProperties);
			}
			else
			{
				//line 31 "/home/travis/haxe/std/sys/Http.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_invokeField(java.lang.String field, java.lang.Object[] dynargs)
	{
		//line 31 "/home/travis/haxe/std/sys/Http.hx"
		{
			//line 31 "/home/travis/haxe/std/sys/Http.hx"
			boolean __temp_executeDef1 = true;
			//line 31 "/home/travis/haxe/std/sys/Http.hx"
			if (( field != null )) 
			{
				//line 31 "/home/travis/haxe/std/sys/Http.hx"
				switch (field.hashCode())
				{
					case 1095692943:
					{
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						if (field.equals("request")) 
						{
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							__temp_executeDef1 = false;
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							return haxe.lang.Runtime.slowCallField(this, field, dynargs);
						}
						
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						break;
					}
					
					
					case 397859789:
					{
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						if (field.equals("fileTransfert")) 
						{
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							__temp_executeDef1 = false;
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							this.fileTransfert(haxe.lang.Runtime.toString(dynargs[0]), haxe.lang.Runtime.toString(dynargs[1]), ((haxe.io.Input) (dynargs[2]) ), ((int) (haxe.lang.Runtime.toInt(dynargs[3])) ), haxe.lang.Runtime.toString(( (( dynargs.length > 4 )) ? (dynargs[4]) : (null) )));
						}
						
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						break;
					}
					
					
					case -1139644809:
					{
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						if (field.equals("readChunk")) 
						{
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							__temp_executeDef1 = false;
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							return this.readChunk(((haxe.root.EReg) (dynargs[0]) ), ((haxe.io.Output) (dynargs[1]) ), ((haxe.io.Bytes) (dynargs[2]) ), ((int) (haxe.lang.Runtime.toInt(dynargs[3])) ));
						}
						
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						break;
					}
					
					
					case 12834183:
					{
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						if (field.equals("fileTransfer")) 
						{
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							__temp_executeDef1 = false;
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							this.fileTransfer(haxe.lang.Runtime.toString(dynargs[0]), haxe.lang.Runtime.toString(dynargs[1]), ((haxe.io.Input) (dynargs[2]) ), ((int) (haxe.lang.Runtime.toInt(dynargs[3])) ), haxe.lang.Runtime.toString(( (( dynargs.length > 4 )) ? (dynargs[4]) : (null) )));
						}
						
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						break;
					}
					
					
					case -954305121:
					{
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						if (field.equals("readHttpResponse")) 
						{
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							__temp_executeDef1 = false;
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							this.readHttpResponse(((haxe.io.Output) (dynargs[0]) ), ((sys.net.Socket) (dynargs[1]) ));
						}
						
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						break;
					}
					
					
					case 2113105374:
					{
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						if (field.equals("customRequest")) 
						{
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							__temp_executeDef1 = false;
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							this.customRequest(haxe.lang.Runtime.toBool(((java.lang.Boolean) (dynargs[0]) )), ((haxe.io.Output) (dynargs[1]) ), ((sys.net.Socket) (( (( dynargs.length > 2 )) ? (dynargs[2]) : (null) )) ), haxe.lang.Runtime.toString(( (( dynargs.length > 3 )) ? (dynargs[3]) : (null) )));
						}
						
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						break;
					}
					
					
					case -1406861791:
					{
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						if (field.equals("writeBody")) 
						{
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							__temp_executeDef1 = false;
							//line 31 "/home/travis/haxe/std/sys/Http.hx"
							this.writeBody(((haxe.io.BytesOutput) (dynargs[0]) ), ((haxe.io.Input) (dynargs[1]) ), ((int) (haxe.lang.Runtime.toInt(dynargs[2])) ), haxe.lang.Runtime.toString(dynargs[3]), ((sys.net.Socket) (dynargs[4]) ));
						}
						
						//line 31 "/home/travis/haxe/std/sys/Http.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 31 "/home/travis/haxe/std/sys/Http.hx"
			if (__temp_executeDef1) 
			{
				//line 31 "/home/travis/haxe/std/sys/Http.hx"
				return super.__hx_invokeField(field, dynargs);
			}
			
		}
		
		//line 31 "/home/travis/haxe/std/sys/Http.hx"
		return null;
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<java.lang.String> baseArr)
	{
		//line 31 "/home/travis/haxe/std/sys/Http.hx"
		baseArr.push("file");
		//line 31 "/home/travis/haxe/std/sys/Http.hx"
		baseArr.push("chunk_buf");
		//line 31 "/home/travis/haxe/std/sys/Http.hx"
		baseArr.push("chunk_size");
		//line 31 "/home/travis/haxe/std/sys/Http.hx"
		baseArr.push("responseHeaders");
		//line 31 "/home/travis/haxe/std/sys/Http.hx"
		baseArr.push("cnxTimeout");
		//line 31 "/home/travis/haxe/std/sys/Http.hx"
		baseArr.push("noShutdown");
		//line 31 "/home/travis/haxe/std/sys/Http.hx"
		super.__hx_getFields(baseArr);
	}
	
	
}


