// Generated by Haxe 4.0.5
package haxe.ds;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class WeakMap<K, V> extends haxe.lang.HxObject implements haxe.IMap<K, V>
{
	public WeakMap(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public WeakMap()
	{
		//line 66 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		haxe.ds.WeakMap.__hx_ctor_haxe_ds_WeakMap(((haxe.ds.WeakMap<K, V>) (this) ));
		//line 66 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		java.lang.Object __temp_expr1 = ((java.lang.Object) (null) );
	}
	
	
	protected static <K_c, V_c> void __hx_ctor_haxe_ds_WeakMap(haxe.ds.WeakMap<K_c, V_c> __hx_this)
	{
		//line 68 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		__hx_this.cachedIndex = -1;
		//line 70 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		__hx_this.queue = new java.lang.ref.ReferenceQueue<K_c>();
	}
	
	
	public int[] hashes;
	
	public haxe.ds._WeakMap.Entry<K, V>[] entries;
	
	public java.lang.ref.ReferenceQueue<K> queue;
	
	public int nBuckets;
	
	public int size;
	
	public int nOccupied;
	
	public int upperBound;
	
	public haxe.ds._WeakMap.Entry<K, V> cachedEntry;
	
	public int cachedIndex;
	
	public void cleanupRefs()
	{
		//line 75 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		java.lang.Object x = null;
		//line 75 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		int nOccupied = this.nOccupied;
		//line 76 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		while (( ! (( (x = this.queue.poll()) == null )) ))
		{
			//line 78 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			haxe.ds._WeakMap.Entry<K, V> x1 = ((haxe.ds._WeakMap.Entry<K, V>) (x) );
			//line 79 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			x1.value = null;
			//line 82 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			if (( nOccupied != 0 )) 
			{
				//line 83 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				int mask = ( this.nBuckets - 1 );
				//line 83 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				int hash = x1.hash;
				//line 83 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				int nProbes = 0;
				//line 84 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				int i = ( hash & mask );
				//line 85 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				int last = i;
				//line 85 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				int flag = 0;
				//line 86 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				do 
				{
					//line 86 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
					boolean __temp_stmt4 = false;
					//line 86 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
					{
						//line 86 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						int v = flag = this.hashes[i];
						//line 86 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						__temp_stmt4 = ( v == 0 );
					}
					
					//line 86 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
					boolean __temp_boolv3 =  ! (__temp_stmt4) ;
					//line 86 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
					boolean __temp_boolv2 = false;
					//line 86 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
					if (__temp_boolv3) 
					{
						//line 86 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						__temp_boolv2 = (( ( ( flag == 1 ) || ( flag != hash ) ) || ( this.entries[i] != x1 ) ));
					}
					
					//line 86 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
					boolean __temp_stmt1 = ( __temp_boolv3 && __temp_boolv2 );
					//line 87 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
					if (__temp_stmt1) 
					{
						//line 87 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						i = ( ( i +  ++ nProbes ) & mask );
					}
					else
					{
						//line 87 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
				}
				while (true);
				//line 90 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				if (( this.entries[i] == x1 )) 
				{
					//line 92 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
					if (( this.cachedIndex == i )) 
					{
						//line 93 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						this.cachedIndex = -1;
						//line 94 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						this.cachedEntry = null;
					}
					
					//line 97 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
					this.entries[i] = null;
					//line 98 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
					this.hashes[i] = 1;
					//line 99 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
					 -- this.size;
				}
				
			}
			
		}
		
	}
	
	
	public void set(K key, V value)
	{
		//line 106 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		this.cleanupRefs();
		//line 107 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		int x = 0;
		//line 108 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		if (( this.nOccupied >= this.upperBound )) 
		{
			//line 109 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			if (( this.nBuckets > ( this.size << 1 ) )) 
			{
				//line 110 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				this.resize(( this.nBuckets - 1 ));
			}
			else
			{
				//line 112 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				this.resize(( this.nBuckets + 2 ));
			}
			
		}
		
		//line 115 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		int k = ((java.lang.Object) (key) ).hashCode();
		//line 115 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		k = ( ( k + 2127912214 ) + (( k << 12 )) );
		//line 115 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		k = ( ( k ^ -949894596 ) ^ ( k >> 19 ) );
		//line 115 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		k = ( ( k + 374761393 ) + (( k << 5 )) );
		//line 115 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		k = ( ( k + (-744332180) ) ^ ( k << 9 ) );
		//line 115 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		k = ( ( k + (-42973499) ) + (( k << 3 )) );
		//line 115 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		k = ( ( k ^ -1252372727 ) ^ ( k >> 16 ) );
		//line 115 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		int ret = k;
		//line 115 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		if (( (( ret & -2 )) == 0 )) 
		{
			//line 115 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			if (( ret == 0 )) 
			{
				//line 115 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				ret = 2;
			}
			else
			{
				//line 115 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				ret = -1;
			}
			
		}
		
		//line 107 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		int k1 = ret;
		//line 116 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		int[] hashes = this.hashes;
		//line 116 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		haxe.ds._WeakMap.Entry<K, V>[] entries = this.entries;
		//line 117 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		{
			//line 118 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			int mask = ( (( this.nBuckets == 0 )) ? (0) : (( this.nBuckets - 1 )) );
			//line 119 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			x = this.nBuckets;
			//line 119 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			int site = x;
			//line 120 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			int i = ( k1 & mask );
			//line 120 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			int nProbes = 0;
			//line 122 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			int delKey = -1;
			//line 124 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			if (( hashes[i] == 0 )) 
			{
				//line 125 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				x = i;
			}
			else
			{
				//line 128 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				int last = i;
				//line 128 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				int flag = 0;
				//line 129 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				while (true)
				{
					//line 129 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
					flag = hashes[i];
					//line 129 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
					if ( ! (( ! ((( ( flag == 0 ) || ( ( flag == k1 ) && (( ( ! (( key == null )) ) && ((java.lang.Object) (key) ).equals(entries[i].get()) )) ) ))) )) ) 
					{
						//line 129 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					//line 130 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
					if (( ( delKey == -1 ) && ( flag == 1 ) )) 
					{
						//line 131 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						delKey = i;
					}
					
					//line 132 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
					i = ( ( i +  ++ nProbes ) & mask );
				}
				
				//line 140 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				if (( ( flag == 0 ) && ( delKey != -1 ) )) 
				{
					//line 141 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
					x = delKey;
				}
				else
				{
					//line 143 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
					x = i;
				}
				
			}
			
		}
		
		//line 153 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		int flag1 = hashes[x];
		//line 153 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		haxe.ds._WeakMap.Entry<K, V> entry = new haxe.ds._WeakMap.Entry<K, V>(key, value, k1, this.queue);
		//line 154 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		if (( flag1 == 0 )) 
		{
			//line 155 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			entries[x] = entry;
			//line 156 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			hashes[x] = k1;
			//line 157 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			this.size++;
			//line 158 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			this.nOccupied++;
		}
		else
		{
			//line 159 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			if (( flag1 == 1 )) 
			{
				//line 160 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				entries[x] = entry;
				//line 161 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				hashes[x] = k1;
				//line 162 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				this.size++;
			}
			else
			{
				//line 164 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				boolean x1 = ( ( ! (( key == null )) ) && ((java.lang.Object) (key) ).equals(entries[x].get()) );
				//line 165 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				entries[x] = entry;
			}
			
		}
		
		//line 169 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		this.cachedIndex = x;
		//line 170 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		this.cachedEntry = entry;
	}
	
	
	public int lookup(K key)
	{
		//line 175 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		if (( this.nBuckets != 0 )) 
		{
			//line 176 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			int[] hashes = this.hashes;
			//line 176 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			haxe.ds._WeakMap.Entry<K, V>[] entries = this.entries;
			//line 178 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			int mask = ( this.nBuckets - 1 );
			//line 178 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			int k = ((java.lang.Object) (key) ).hashCode();
			//line 178 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			k = ( ( k + 2127912214 ) + (( k << 12 )) );
			//line 178 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			k = ( ( k ^ -949894596 ) ^ ( k >> 19 ) );
			//line 178 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			k = ( ( k + 374761393 ) + (( k << 5 )) );
			//line 178 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			k = ( ( k + (-744332180) ) ^ ( k << 9 ) );
			//line 178 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			k = ( ( k + (-42973499) ) + (( k << 3 )) );
			//line 178 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			k = ( ( k ^ -1252372727 ) ^ ( k >> 16 ) );
			//line 178 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			int ret = k;
			//line 178 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			if (( (( ret & -2 )) == 0 )) 
			{
				//line 178 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				if (( ret == 0 )) 
				{
					//line 178 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
					ret = 2;
				}
				else
				{
					//line 178 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
					ret = -1;
				}
				
			}
			
			//line 178 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			int hash = ret;
			//line 178 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			int k1 = hash;
			//line 178 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			int nProbes = 0;
			//line 179 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			int i = ( k1 & mask );
			//line 180 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			int last = i;
			//line 180 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			int flag = 0;
			//line 182 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			while (true)
			{
				//line 182 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				flag = hashes[i];
				//line 182 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				if ( ! ((( ( flag != 0 ) && (( ( ( flag == 1 ) || ( flag != k1 ) ) ||  ! ((( ( ! (( key == null )) ) && ((java.lang.Object) (key) ).equals(entries[i].get()) )))  )) ))) ) 
				{
					//line 182 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
					break;
				}
				
				//line 183 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				i = ( ( i +  ++ nProbes ) & mask );
			}
			
			//line 196 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			if (( (( flag & -2 )) == 0 )) 
			{
				//line 196 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				return -1;
			}
			else
			{
				//line 196 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				return i;
			}
			
		}
		
		//line 199 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		return -1;
	}
	
	
	public void resize(int newNBuckets)
	{
		//line 204 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		int[] newHash = null;
		//line 205 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		int j = 1;
		//line 206 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		{
			//line 207 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			int x = newNBuckets;
			//line 207 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			 -- x;
			//line 207 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			x |= ( x >>> 1 );
			//line 207 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			x |= ( x >>> 2 );
			//line 207 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			x |= ( x >>> 4 );
			//line 207 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			x |= ( x >>> 8 );
			//line 207 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			x |= ( x >>> 16 );
			//line 207 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			 ++ x;
			//line 207 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			newNBuckets = x;
			//line 208 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			if (( newNBuckets < 4 )) 
			{
				//line 209 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				newNBuckets = 4;
			}
			
			//line 210 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			if (( this.size >= ( ( newNBuckets * 0.77 ) + 0.5 ) )) 
			{
				//line 212 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				j = 0;
			}
			else
			{
				//line 214 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				int nfSize = newNBuckets;
				//line 215 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				newHash = new int[nfSize];
				//line 216 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				if (( this.nBuckets < newNBuckets )) 
				{
					//line 218 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
					haxe.ds._WeakMap.Entry<K, V>[] e = new haxe.ds._WeakMap.Entry[newNBuckets];
					//line 219 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
					if (( this.entries != null )) 
					{
						//line 220 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						java.lang.System.arraycopy(((java.lang.Object) (this.entries) ), ((int) (0) ), ((java.lang.Object) (e) ), ((int) (0) ), ((int) (this.nBuckets) ));
					}
					
					//line 221 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
					this.entries = e;
				}
				
			}
			
		}
		
		//line 226 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		if (( j != 0 )) 
		{
			//line 229 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			this.cachedEntry = null;
			//line 230 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			this.cachedIndex = -1;
			//line 233 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			j = -1;
			//line 234 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			int nBuckets = this.nBuckets;
			//line 234 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			haxe.ds._WeakMap.Entry<K, V>[] entries = this.entries;
			//line 234 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			int[] hashes = this.hashes;
			//line 236 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			int newMask = ( newNBuckets - 1 );
			//line 237 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			while ((  ++ j < nBuckets ))
			{
				//line 238 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				int k = hashes[j];
				//line 239 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				if (( (( k & -2 )) != 0 )) 
				{
					//line 240 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
					haxe.ds._WeakMap.Entry<K, V> entry = entries[j];
					//line 242 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
					entries[j] = null;
					//line 243 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
					hashes[j] = 1;
					//line 244 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
					while (true)
					{
						//line 246 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						int nProbes = 0;
						//line 247 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						int i = ( k & newMask );
						//line 249 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						while (( newHash[i] != 0 ))
						{
							//line 250 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							i = ( ( i +  ++ nProbes ) & newMask );
						}
						
						//line 252 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						newHash[i] = k;
						//line 254 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						boolean tmp = false;
						//line 254 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (( i < nBuckets )) 
						{
							//line 254 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							k = hashes[i];
							//line 254 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							tmp = ( (( k & -2 )) != 0 );
						}
						else
						{
							//line 254 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							tmp = false;
						}
						
						//line 254 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (tmp) 
						{
							//line 256 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							{
								//line 257 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
								haxe.ds._WeakMap.Entry<K, V> tmp1 = entries[i];
								//line 258 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
								entries[i] = entry;
								//line 259 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
								entry = tmp1;
							}
							
							//line 262 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							hashes[i] = 1;
						}
						else
						{
							//line 264 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							entries[i] = entry;
							//line 265 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							break;
						}
						
					}
					
				}
				
			}
			
			//line 271 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			if (( nBuckets > newNBuckets )) 
			{
				//line 274 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				haxe.ds._WeakMap.Entry<K, V>[] e1 = new haxe.ds._WeakMap.Entry[newNBuckets];
				//line 275 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				java.lang.System.arraycopy(((java.lang.Object) (entries) ), ((int) (0) ), ((java.lang.Object) (e1) ), ((int) (0) ), ((int) (newNBuckets) ));
				//line 276 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				this.entries = e1;
			}
			
			//line 280 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			this.hashes = newHash;
			//line 281 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			this.nBuckets = newNBuckets;
			//line 282 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			this.nOccupied = this.size;
			//line 283 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			this.upperBound = ((int) (( ( newNBuckets * 0.77 ) + .5 )) );
		}
		
	}
	
	
	public java.lang.Object get(K key)
	{
		//line 288 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		this.cleanupRefs();
		//line 289 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		int idx = -1;
		//line 291 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		boolean tmp = false;
		//line 291 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		if (( ( this.cachedEntry != null ) && (( ( ! (( key == null )) ) && ((java.lang.Object) (key) ).equals(this.cachedEntry.get()) )) )) 
		{
			//line 291 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			idx = this.cachedIndex;
			//line 291 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			tmp = ( idx != -1 );
		}
		else
		{
			//line 291 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			tmp = false;
		}
		
		//line 291 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		if (tmp) 
		{
			//line 292 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			return this.cachedEntry.value;
		}
		
		//line 296 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		idx = this.lookup(key);
		//line 297 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		if (( idx != -1 )) 
		{
			//line 298 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			haxe.ds._WeakMap.Entry<K, V> entry = this.entries[idx];
			//line 300 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			this.cachedEntry = entry;
			//line 301 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			this.cachedIndex = idx;
			//line 304 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			return entry.value;
		}
		
		//line 307 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		return null;
	}
	
	
	public V getDefault(K key, V def)
	{
		//line 311 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		this.cleanupRefs();
		//line 312 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		int idx = -1;
		//line 314 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		boolean tmp = false;
		//line 314 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		if (( ( this.cachedEntry != null ) && (( ( ! (( key == null )) ) && ((java.lang.Object) (key) ).equals(this.cachedEntry.get()) )) )) 
		{
			//line 314 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			idx = this.cachedIndex;
			//line 314 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			tmp = ( idx != -1 );
		}
		else
		{
			//line 314 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			tmp = false;
		}
		
		//line 314 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		if (tmp) 
		{
			//line 315 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			return this.cachedEntry.value;
		}
		
		//line 319 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		idx = this.lookup(key);
		//line 320 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		if (( idx != -1 )) 
		{
			//line 321 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			haxe.ds._WeakMap.Entry<K, V> entry = this.entries[idx];
			//line 323 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			this.cachedEntry = entry;
			//line 324 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			this.cachedIndex = idx;
			//line 327 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			return entry.value;
		}
		
		//line 330 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		return def;
	}
	
	
	public boolean exists(K key)
	{
		//line 334 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		this.cleanupRefs();
		//line 335 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		int idx = -1;
		//line 337 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		boolean tmp = false;
		//line 337 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		if (( ( this.cachedEntry != null ) && (( ( ! (( key == null )) ) && ((java.lang.Object) (key) ).equals(this.cachedEntry.get()) )) )) 
		{
			//line 337 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			idx = this.cachedIndex;
			//line 337 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			tmp = ( idx != -1 );
		}
		else
		{
			//line 337 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			tmp = false;
		}
		
		//line 337 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		if (tmp) 
		{
			//line 338 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			return true;
		}
		
		//line 342 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		idx = this.lookup(key);
		//line 343 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		if (( idx != -1 )) 
		{
			//line 344 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			haxe.ds._WeakMap.Entry<K, V> entry = this.entries[idx];
			//line 346 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			this.cachedEntry = entry;
			//line 347 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			this.cachedIndex = idx;
			//line 350 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			return true;
		}
		
		//line 353 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		return false;
	}
	
	
	public boolean remove(K key)
	{
		//line 357 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		this.cleanupRefs();
		//line 358 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		int idx = -1;
		//line 360 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		boolean tmp = false;
		//line 360 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		if (( ( this.cachedEntry != null ) && (( ( ! (( key == null )) ) && ((java.lang.Object) (key) ).equals(this.cachedEntry.get()) )) )) 
		{
			//line 360 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			idx = this.cachedIndex;
			//line 360 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			tmp = ( idx != -1 );
		}
		else
		{
			//line 360 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			tmp = false;
		}
		
		//line 360 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		if ( ! (tmp) ) 
		{
			//line 363 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			idx = this.lookup(key);
		}
		
		//line 366 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		if (( idx == -1 )) 
		{
			//line 367 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			return false;
		}
		else
		{
			//line 370 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			if (( ( this.cachedEntry != null ) && (( ( ! (( key == null )) ) && ((java.lang.Object) (key) ).equals(this.cachedEntry.get()) )) )) 
			{
				//line 371 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				this.cachedIndex = -1;
				//line 372 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				this.cachedEntry = null;
			}
			
			//line 376 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			this.hashes[idx] = 1;
			//line 377 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			this.entries[idx] = null;
			//line 378 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			 -- this.size;
			//line 380 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			return true;
		}
		
	}
	
	
	public final java.lang.Object keys()
	{
		//line 385 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		this.cleanupRefs();
		//line 386 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		return new haxe.ds._WeakMap.WeakMapKeyIterator<K, V>(((haxe.ds.WeakMap<K, V>) (this) ));
	}
	
	
	public final java.lang.Object iterator()
	{
		//line 390 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		this.cleanupRefs();
		//line 391 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		return new haxe.ds._WeakMap.WeakMapValueIterator<K, V>(((haxe.ds.WeakMap<K, V>) (this) ));
	}
	
	
	public final java.lang.Object keyValueIterator()
	{
		//line 395 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		return new haxe.iterators.MapKeyValueIterator<K, V>(((haxe.IMap<K, V>) (this) ));
	}
	
	
	public haxe.ds.WeakMap<K, V> copy()
	{
		//line 399 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		haxe.ds.WeakMap<K, java.lang.Object> copied = new haxe.ds.WeakMap<K, java.lang.Object>();
		//line 400 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		{
			//line 400 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			this.cleanupRefs();
			//line 400 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			java.lang.Object key = ((java.lang.Object) (new haxe.ds._WeakMap.WeakMapKeyIterator<K, V>(((haxe.ds.WeakMap<K, V>) (this) ))) );
			//line 400 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			while (haxe.lang.Runtime.toBool(((java.lang.Boolean) (haxe.lang.Runtime.callField(key, "hasNext", null)) )))
			{
				//line 400 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				K key1 = ((K) (haxe.lang.Runtime.callField(key, "next", null)) );
				//line 401 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				copied.set(key1, this.get(key1));
			}
			
		}
		
		//line 402 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		return ((haxe.ds.WeakMap<K, V>) (((haxe.ds.WeakMap) (copied) )) );
	}
	
	
	@Override public java.lang.String toString()
	{
		//line 406 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		haxe.root.StringBuf s = new haxe.root.StringBuf();
		//line 407 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		s.add(haxe.lang.Runtime.toString("{"));
		//line 407 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		java.lang.Object __temp_expr1 = ((java.lang.Object) (null) );
		//line 408 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		this.cleanupRefs();
		//line 408 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		java.lang.Object it = ((java.lang.Object) (new haxe.ds._WeakMap.WeakMapKeyIterator<K, V>(((haxe.ds.WeakMap<K, V>) (this) ))) );
		//line 409 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		{
			//line 409 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			java.lang.Object i = it;
			//line 409 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			while (haxe.lang.Runtime.toBool(((java.lang.Boolean) (haxe.lang.Runtime.callField(i, "hasNext", null)) )))
			{
				//line 409 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				K i1 = ((K) (haxe.lang.Runtime.callField(i, "next", null)) );
				//line 410 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				s.add(haxe.lang.Runtime.toString(haxe.root.Std.string(i1)));
				//line 410 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				java.lang.Object __temp_expr2 = ((java.lang.Object) (null) );
				//line 411 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				s.add(haxe.lang.Runtime.toString(" => "));
				//line 411 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				java.lang.Object __temp_expr3 = ((java.lang.Object) (null) );
				//line 412 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				s.add(haxe.lang.Runtime.toString(haxe.root.Std.string(this.get(i1))));
				//line 412 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				java.lang.Object __temp_expr4 = ((java.lang.Object) (null) );
				//line 413 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				if (haxe.lang.Runtime.toBool(((java.lang.Boolean) (haxe.lang.Runtime.callField(it, "hasNext", null)) ))) 
				{
					//line 414 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
					s.add(haxe.lang.Runtime.toString(", "));
					//line 414 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
					java.lang.Object __temp_expr5 = ((java.lang.Object) (null) );
				}
				
			}
			
		}
		
		//line 416 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		s.add(haxe.lang.Runtime.toString("}"));
		//line 416 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		java.lang.Object __temp_expr6 = ((java.lang.Object) (null) );
		//line 417 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		return s.toString();
	}
	
	
	public void clear()
	{
		//line 421 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		this.hashes = null;
		//line 422 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		this.entries = null;
		//line 423 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		this.queue = new java.lang.ref.ReferenceQueue<K>();
		//line 424 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		this.nBuckets = 0;
		//line 425 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		this.size = 0;
		//line 426 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		this.nOccupied = 0;
		//line 427 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		this.upperBound = 0;
		//line 429 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		this.cachedEntry = null;
		//line 430 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		this.cachedIndex = -1;
	}
	
	
	@Override public double __hx_setField_f(java.lang.String field, double value, boolean handleProperties)
	{
		//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		{
			//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			boolean __temp_executeDef1 = true;
			//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			if (( field != null )) 
			{
				//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				switch (field.hashCode())
				{
					case 1005083856:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("cachedIndex")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							this.cachedIndex = ((int) (value) );
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return value;
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case 325636987:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("nBuckets")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							this.nBuckets = ((int) (value) );
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return value;
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case -1690761732:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("upperBound")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							this.upperBound = ((int) (value) );
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return value;
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case 3530753:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("size")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							this.size = ((int) (value) );
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return value;
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case -394102484:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("nOccupied")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							this.nOccupied = ((int) (value) );
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return value;
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			if (__temp_executeDef1) 
			{
				//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				return super.__hx_setField_f(field, value, handleProperties);
			}
			else
			{
				//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_setField(java.lang.String field, java.lang.Object value, boolean handleProperties)
	{
		//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		{
			//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			boolean __temp_executeDef1 = true;
			//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			if (( field != null )) 
			{
				//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				switch (field.hashCode())
				{
					case 1005083856:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("cachedIndex")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							this.cachedIndex = ((int) (haxe.lang.Runtime.toInt(value)) );
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return value;
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case -1224424900:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("hashes")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							this.hashes = ((int[]) (value) );
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return value;
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case 1001405552:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("cachedEntry")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							this.cachedEntry = ((haxe.ds._WeakMap.Entry<K, V>) (value) );
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return value;
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case -1591573360:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("entries")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							this.entries = ((haxe.ds._WeakMap.Entry<K, V>[]) (value) );
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return value;
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case -1690761732:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("upperBound")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							this.upperBound = ((int) (haxe.lang.Runtime.toInt(value)) );
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return value;
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case 107944209:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("queue")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							this.queue = ((java.lang.ref.ReferenceQueue<K>) (value) );
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return value;
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case -394102484:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("nOccupied")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							this.nOccupied = ((int) (haxe.lang.Runtime.toInt(value)) );
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return value;
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case 325636987:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("nBuckets")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							this.nBuckets = ((int) (haxe.lang.Runtime.toInt(value)) );
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return value;
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case 3530753:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("size")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							this.size = ((int) (haxe.lang.Runtime.toInt(value)) );
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return value;
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			if (__temp_executeDef1) 
			{
				//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				return super.__hx_setField(field, value, handleProperties);
			}
			else
			{
				//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		{
			//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			boolean __temp_executeDef1 = true;
			//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			if (( field != null )) 
			{
				//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				switch (field.hashCode())
				{
					case 94746189:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("clear")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "clear")) );
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case -1224424900:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("hashes")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return this.hashes;
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case -1776922004:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("toString")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "toString")) );
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case -1591573360:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("entries")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return this.entries;
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case 3059573:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("copy")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "copy")) );
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case 107944209:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("queue")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return this.queue;
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case -955047712:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("keyValueIterator")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "keyValueIterator")) );
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case 325636987:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("nBuckets")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return this.nBuckets;
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case 1182533742:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("iterator")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "iterator")) );
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case 3530753:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("size")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return this.size;
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case 3288564:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("keys")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "keys")) );
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case -394102484:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("nOccupied")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return this.nOccupied;
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case -934610812:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("remove")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "remove")) );
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case -1690761732:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("upperBound")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return this.upperBound;
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case -1289358244:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("exists")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "exists")) );
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case 1001405552:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("cachedEntry")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return this.cachedEntry;
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case -1713303029:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("getDefault")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "getDefault")) );
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case 1005083856:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("cachedIndex")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return this.cachedIndex;
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case 102230:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("get")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "get")) );
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case 128201476:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("cleanupRefs")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "cleanupRefs")) );
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case -934437708:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("resize")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "resize")) );
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case 113762:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("set")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "set")) );
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case -1097094790:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("lookup")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "lookup")) );
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			if (__temp_executeDef1) 
			{
				//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public double __hx_getField_f(java.lang.String field, boolean throwErrors, boolean handleProperties)
	{
		//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		{
			//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			boolean __temp_executeDef1 = true;
			//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			if (( field != null )) 
			{
				//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				switch (field.hashCode())
				{
					case 1005083856:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("cachedIndex")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return ((double) (this.cachedIndex) );
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case 325636987:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("nBuckets")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return ((double) (this.nBuckets) );
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case -1690761732:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("upperBound")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return ((double) (this.upperBound) );
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case 3530753:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("size")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return ((double) (this.size) );
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case -394102484:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("nOccupied")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return ((double) (this.nOccupied) );
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			if (__temp_executeDef1) 
			{
				//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				return super.__hx_getField_f(field, throwErrors, handleProperties);
			}
			else
			{
				//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_invokeField(java.lang.String field, java.lang.Object[] dynargs)
	{
		//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		{
			//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			boolean __temp_executeDef1 = true;
			//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			if (( field != null )) 
			{
				//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				switch (field.hashCode())
				{
					case 94746189:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("clear")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							this.clear();
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case 128201476:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("cleanupRefs")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							this.cleanupRefs();
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case -1776922004:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("toString")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return this.toString();
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case 113762:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("set")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							this.set(((K) (dynargs[0]) ), ((V) (dynargs[1]) ));
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case 3059573:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("copy")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return this.copy();
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case -1097094790:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("lookup")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return this.lookup(((K) (dynargs[0]) ));
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case -955047712:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("keyValueIterator")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return this.keyValueIterator();
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case -934437708:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("resize")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							this.resize(((int) (haxe.lang.Runtime.toInt(dynargs[0])) ));
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case 1182533742:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("iterator")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return this.iterator();
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case 102230:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("get")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return this.get(((K) (dynargs[0]) ));
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case 3288564:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("keys")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return this.keys();
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case -1713303029:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("getDefault")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return this.getDefault(((K) (dynargs[0]) ), ((V) (dynargs[1]) ));
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case -934610812:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("remove")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return this.remove(((K) (dynargs[0]) ));
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
					case -1289358244:
					{
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						if (field.equals("exists")) 
						{
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							__temp_executeDef1 = false;
							//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
							return this.exists(((K) (dynargs[0]) ));
						}
						
						//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
			if (__temp_executeDef1) 
			{
				//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
				return super.__hx_invokeField(field, dynargs);
			}
			
		}
		
		//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		return null;
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<java.lang.String> baseArr)
	{
		//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		baseArr.push("cachedIndex");
		//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		baseArr.push("cachedEntry");
		//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		baseArr.push("upperBound");
		//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		baseArr.push("nOccupied");
		//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		baseArr.push("size");
		//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		baseArr.push("nBuckets");
		//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		baseArr.push("queue");
		//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		baseArr.push("entries");
		//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		baseArr.push("hashes");
		//line 29 "/home/travis/haxe/std/java/_std/haxe/ds/WeakMap.hx"
		super.__hx_getFields(baseArr);
	}
	
	
}


