// Generated by Haxe 4.0.5
package connect.api.impl;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class FulfillmentApiImpl extends connect.Base implements connect.api.IFulfillmentApi
{
	static
	{
		//line 9 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
		connect.api.impl.FulfillmentApiImpl.REQUESTS_PATH = "requests";
		//line 10 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
		connect.api.impl.FulfillmentApiImpl.TEMPLATES_PATH = "templates";
		//line 11 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
		connect.api.impl.FulfillmentApiImpl.ASSETS_PATH = "assets";
	}
	
	public FulfillmentApiImpl(haxe.lang.EmptyObject empty)
	{
		//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
		super(haxe.lang.EmptyObject.EMPTY);
	}
	
	
	public FulfillmentApiImpl()
	{
		//line 14 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
		connect.api.impl.FulfillmentApiImpl.__hx_ctor_connect_api_impl_FulfillmentApiImpl(this);
	}
	
	
	protected static void __hx_ctor_connect_api_impl_FulfillmentApiImpl(connect.api.impl.FulfillmentApiImpl __hx_this)
	{
	}
	
	
	public static java.lang.String REQUESTS_PATH;
	
	public static java.lang.String TEMPLATES_PATH;
	
	public static java.lang.String ASSETS_PATH;
	
	public java.lang.String listRequests(connect.api.Query filters)
	{
		//line 18 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
		return connect.api.ConnectHelper.get(connect.api.impl.FulfillmentApiImpl.REQUESTS_PATH, null, null, filters, null);
	}
	
	
	public java.lang.String getRequest(java.lang.String id)
	{
		//line 23 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
		return connect.api.ConnectHelper.get(connect.api.impl.FulfillmentApiImpl.REQUESTS_PATH, id, null, null, null);
	}
	
	
	public java.lang.String createRequest(java.lang.String body)
	{
		//line 28 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
		return connect.api.ConnectHelper.post(connect.api.impl.FulfillmentApiImpl.REQUESTS_PATH, null, null, body);
	}
	
	
	public java.lang.String updateRequest(java.lang.String id, java.lang.String request)
	{
		//line 33 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
		return connect.api.ConnectHelper.put(connect.api.impl.FulfillmentApiImpl.REQUESTS_PATH, id, request);
	}
	
	
	public java.lang.String changeRequestStatus(java.lang.String id, java.lang.String status, java.lang.String data)
	{
		//line 38 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
		return connect.api.ConnectHelper.post(connect.api.impl.FulfillmentApiImpl.REQUESTS_PATH, id, status, data);
	}
	
	
	public java.lang.String assignRequest(java.lang.String id, java.lang.String assignee)
	{
		//line 43 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
		return connect.api.ConnectHelper.post(connect.api.impl.FulfillmentApiImpl.REQUESTS_PATH, id, ( "assign/" + assignee ), null);
	}
	
	
	public java.lang.String renderTemplate(java.lang.String id, java.lang.String request_id)
	{
		//line 48 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
		return connect.api.ConnectHelper.get(connect.api.impl.FulfillmentApiImpl.TEMPLATES_PATH, id, "render", new connect.api.Query().equal("request_id", request_id), null);
	}
	
	
	public java.lang.String listAssets(connect.api.Query filters)
	{
		//line 54 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
		return connect.api.ConnectHelper.get(connect.api.impl.FulfillmentApiImpl.ASSETS_PATH, null, null, filters, true);
	}
	
	
	public java.lang.String getAsset(java.lang.String id)
	{
		//line 59 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
		return connect.api.ConnectHelper.get(connect.api.impl.FulfillmentApiImpl.ASSETS_PATH, id, null, null, null);
	}
	
	
	public java.lang.String getAssetRequests(java.lang.String id)
	{
		//line 64 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
		return connect.api.ConnectHelper.get(connect.api.impl.FulfillmentApiImpl.ASSETS_PATH, id, "requests", null, null);
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
		{
			//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
			boolean __temp_executeDef1 = true;
			//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
			if (( field != null )) 
			{
				//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
				switch (field.hashCode())
				{
					case -252413154:
					{
						//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
						if (field.equals("getAssetRequests")) 
						{
							//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
							__temp_executeDef1 = false;
							//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "getAssetRequests")) );
						}
						
						//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
						break;
					}
					
					
					case 690550402:
					{
						//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
						if (field.equals("listRequests")) 
						{
							//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
							__temp_executeDef1 = false;
							//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "listRequests")) );
						}
						
						//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
						break;
					}
					
					
					case 1948946746:
					{
						//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
						if (field.equals("getAsset")) 
						{
							//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
							__temp_executeDef1 = false;
							//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "getAsset")) );
						}
						
						//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
						break;
					}
					
					
					case 2132553305:
					{
						//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
						if (field.equals("getRequest")) 
						{
							//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
							__temp_executeDef1 = false;
							//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "getRequest")) );
						}
						
						//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
						break;
					}
					
					
					case -151215679:
					{
						//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
						if (field.equals("listAssets")) 
						{
							//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
							__temp_executeDef1 = false;
							//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "listAssets")) );
						}
						
						//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
						break;
					}
					
					
					case -952756749:
					{
						//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
						if (field.equals("createRequest")) 
						{
							//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
							__temp_executeDef1 = false;
							//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "createRequest")) );
						}
						
						//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
						break;
					}
					
					
					case 1118338096:
					{
						//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
						if (field.equals("renderTemplate")) 
						{
							//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
							__temp_executeDef1 = false;
							//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "renderTemplate")) );
						}
						
						//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
						break;
					}
					
					
					case -400257658:
					{
						//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
						if (field.equals("updateRequest")) 
						{
							//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
							__temp_executeDef1 = false;
							//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "updateRequest")) );
						}
						
						//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
						break;
					}
					
					
					case -668995936:
					{
						//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
						if (field.equals("assignRequest")) 
						{
							//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
							__temp_executeDef1 = false;
							//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "assignRequest")) );
						}
						
						//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
						break;
					}
					
					
					case -1472667247:
					{
						//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
						if (field.equals("changeRequestStatus")) 
						{
							//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
							__temp_executeDef1 = false;
							//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "changeRequestStatus")) );
						}
						
						//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
			if (__temp_executeDef1) 
			{
				//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_invokeField(java.lang.String field, java.lang.Object[] dynargs)
	{
		//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
		{
			//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
			boolean __temp_executeDef1 = true;
			//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
			if (( field != null )) 
			{
				//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
				switch (field.hashCode())
				{
					case -252413154:
					{
						//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
						if (field.equals("getAssetRequests")) 
						{
							//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
							__temp_executeDef1 = false;
							//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
							return this.getAssetRequests(haxe.lang.Runtime.toString(dynargs[0]));
						}
						
						//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
						break;
					}
					
					
					case 690550402:
					{
						//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
						if (field.equals("listRequests")) 
						{
							//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
							__temp_executeDef1 = false;
							//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
							return this.listRequests(((connect.api.Query) (dynargs[0]) ));
						}
						
						//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
						break;
					}
					
					
					case 1948946746:
					{
						//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
						if (field.equals("getAsset")) 
						{
							//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
							__temp_executeDef1 = false;
							//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
							return this.getAsset(haxe.lang.Runtime.toString(dynargs[0]));
						}
						
						//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
						break;
					}
					
					
					case 2132553305:
					{
						//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
						if (field.equals("getRequest")) 
						{
							//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
							__temp_executeDef1 = false;
							//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
							return this.getRequest(haxe.lang.Runtime.toString(dynargs[0]));
						}
						
						//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
						break;
					}
					
					
					case -151215679:
					{
						//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
						if (field.equals("listAssets")) 
						{
							//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
							__temp_executeDef1 = false;
							//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
							return this.listAssets(((connect.api.Query) (dynargs[0]) ));
						}
						
						//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
						break;
					}
					
					
					case -952756749:
					{
						//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
						if (field.equals("createRequest")) 
						{
							//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
							__temp_executeDef1 = false;
							//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
							return this.createRequest(haxe.lang.Runtime.toString(dynargs[0]));
						}
						
						//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
						break;
					}
					
					
					case 1118338096:
					{
						//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
						if (field.equals("renderTemplate")) 
						{
							//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
							__temp_executeDef1 = false;
							//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
							return this.renderTemplate(haxe.lang.Runtime.toString(dynargs[0]), haxe.lang.Runtime.toString(dynargs[1]));
						}
						
						//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
						break;
					}
					
					
					case -400257658:
					{
						//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
						if (field.equals("updateRequest")) 
						{
							//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
							__temp_executeDef1 = false;
							//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
							return this.updateRequest(haxe.lang.Runtime.toString(dynargs[0]), haxe.lang.Runtime.toString(dynargs[1]));
						}
						
						//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
						break;
					}
					
					
					case -668995936:
					{
						//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
						if (field.equals("assignRequest")) 
						{
							//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
							__temp_executeDef1 = false;
							//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
							return this.assignRequest(haxe.lang.Runtime.toString(dynargs[0]), haxe.lang.Runtime.toString(dynargs[1]));
						}
						
						//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
						break;
					}
					
					
					case -1472667247:
					{
						//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
						if (field.equals("changeRequestStatus")) 
						{
							//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
							__temp_executeDef1 = false;
							//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
							return this.changeRequestStatus(haxe.lang.Runtime.toString(dynargs[0]), haxe.lang.Runtime.toString(dynargs[1]), haxe.lang.Runtime.toString(dynargs[2]));
						}
						
						//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
			if (__temp_executeDef1) 
			{
				//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
				return super.__hx_invokeField(field, dynargs);
			}
			else
			{
				//line 8 "/home/travis/build/JaviCerveraIngram/connect-haxe-sdk/connect/api/impl/FulfillmentApiImpl.hx"
				throw null;
			}
			
		}
		
	}
	
	
}


