// Generated by Haxe 4.0.5
package connect.util;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Blob extends connect.Base
{
	public Blob(haxe.lang.EmptyObject empty)
	{
		//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
		super(((haxe.lang.EmptyObject) (haxe.lang.EmptyObject.EMPTY) ));
	}
	
	
	public Blob(haxe.io.Bytes bytes)
	{
		//line 61 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
		connect.util.Blob.__hx_ctor_connect_util_Blob(this, bytes);
	}
	
	
	protected static void __hx_ctor_connect_util_Blob(connect.util.Blob __hx_this, haxe.io.Bytes bytes)
	{
		//line 62 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
		__hx_this.bytes = bytes;
	}
	
	
	public static connect.util.Blob load(java.lang.String path)
	{
		//line 18 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
		return new connect.util.Blob(((haxe.io.Bytes) (sys.io.File.getBytes(path)) ));
	}
	
	
	public static connect.util.Blob _fromBytes(haxe.io.Bytes bytes)
	{
		//line 36 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
		return new connect.util.Blob(((haxe.io.Bytes) (bytes) ));
	}
	
	
	public static haxe.root.Array<java.lang.Object> _bytesToArray(haxe.io.Bytes bytes)
	{
		//line 54 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
		haxe.root.Array<java.lang.Object> _g = new haxe.root.Array<java.lang.Object>(new java.lang.Object[]{});
		//line 54 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
		{
			//line 54 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
			int _g1 = 0;
			//line 54 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
			haxe.io.ArrayBufferViewImpl _g2 = haxe.io._UInt8Array.UInt8Array_Impl_.fromBytes(bytes, null, null);
			//line 54 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
			while (( _g1 < ((haxe.io.ArrayBufferViewImpl) (_g2) ).byteLength ))
			{
				//line 54 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
				int b = ( ((haxe.io.ArrayBufferViewImpl) (_g2) ).bytes.b[( _g1 + ((haxe.io.ArrayBufferViewImpl) (_g2) ).byteOffset )] & 255 );
				//line 54 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
				 ++ _g1;
				//line 54 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
				_g.push(b);
			}
			
		}
		
		//line 54 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
		return _g;
	}
	
	
	public int length()
	{
		//line 24 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
		return this.bytes.length;
	}
	
	
	@Override public java.lang.String toString()
	{
		//line 30 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
		return this.bytes.toString();
	}
	
	
	public haxe.io.Bytes _getBytes()
	{
		//line 42 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
		return this.bytes;
	}
	
	
	public haxe.root.Array<java.lang.Object> _toArray()
	{
		//line 48 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
		return connect.util.Blob._bytesToArray(this._getBytes());
	}
	
	
	public haxe.io.Bytes bytes;
	
	@Override public java.lang.Object __hx_setField(java.lang.String field, java.lang.Object value, boolean handleProperties)
	{
		//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
		{
			//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
			boolean __temp_executeDef1 = true;
			//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
			if (( field != null )) 
			{
				//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
				switch (field.hashCode())
				{
					case 94224491:
					{
						//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
						if (field.equals("bytes")) 
						{
							//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
							__temp_executeDef1 = false;
							//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
							this.bytes = ((haxe.io.Bytes) (value) );
							//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
							return value;
						}
						
						//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
			if (__temp_executeDef1) 
			{
				//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
				return super.__hx_setField(field, value, handleProperties);
			}
			else
			{
				//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
		{
			//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
			boolean __temp_executeDef1 = true;
			//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
			if (( field != null )) 
			{
				//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
				switch (field.hashCode())
				{
					case 94224491:
					{
						//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
						if (field.equals("bytes")) 
						{
							//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
							__temp_executeDef1 = false;
							//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
							return this.bytes;
						}
						
						//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
						break;
					}
					
					
					case -1106363674:
					{
						//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
						if (field.equals("length")) 
						{
							//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
							__temp_executeDef1 = false;
							//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "length")) );
						}
						
						//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
						break;
					}
					
					
					case 1175842655:
					{
						//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
						if (field.equals("_toArray")) 
						{
							//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
							__temp_executeDef1 = false;
							//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "_toArray")) );
						}
						
						//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
						break;
					}
					
					
					case -1776922004:
					{
						//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
						if (field.equals("toString")) 
						{
							//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
							__temp_executeDef1 = false;
							//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "toString")) );
						}
						
						//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
						break;
					}
					
					
					case 2040567828:
					{
						//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
						if (field.equals("_getBytes")) 
						{
							//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
							__temp_executeDef1 = false;
							//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "_getBytes")) );
						}
						
						//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
			if (__temp_executeDef1) 
			{
				//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_invokeField(java.lang.String field, java.lang.Object[] dynargs)
	{
		//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
		{
			//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
			boolean __temp_executeDef1 = true;
			//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
			if (( field != null )) 
			{
				//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
				switch (field.hashCode())
				{
					case 1175842655:
					{
						//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
						if (field.equals("_toArray")) 
						{
							//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
							__temp_executeDef1 = false;
							//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
							return this._toArray();
						}
						
						//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
						break;
					}
					
					
					case -1106363674:
					{
						//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
						if (field.equals("length")) 
						{
							//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
							__temp_executeDef1 = false;
							//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
							return this.length();
						}
						
						//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
						break;
					}
					
					
					case 2040567828:
					{
						//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
						if (field.equals("_getBytes")) 
						{
							//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
							__temp_executeDef1 = false;
							//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
							return this._getBytes();
						}
						
						//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
						break;
					}
					
					
					case -1776922004:
					{
						//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
						if (field.equals("toString")) 
						{
							//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
							__temp_executeDef1 = false;
							//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
							return this.toString();
						}
						
						//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
			if (__temp_executeDef1) 
			{
				//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
				return super.__hx_invokeField(field, dynargs);
			}
			else
			{
				//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<java.lang.String> baseArr)
	{
		//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
		baseArr.push("bytes");
		//line 15 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Blob.hx"
		super.__hx_getFields(baseArr);
	}
	
	
}


