// Generated by Haxe 4.0.5
package connect.util;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Diff_parse_213__Fun extends haxe.lang.Function
{
	public Diff_parse_213__Fun(java.lang.Object obj, haxe.ds.StringMap changes)
	{
		//line 213 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Diff.hx"
		super(1, 0);
		//line 213 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Diff.hx"
		this.obj = obj;
		//line 213 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Diff.hx"
		this.changes = changes;
	}
	
	
	@Override public java.lang.Object __hx_invoke1_o(double __fn_float1, java.lang.Object __fn_dyn1)
	{
		//line 213 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Diff.hx"
		java.lang.String f2 = ( (( __fn_dyn1 == haxe.lang.Runtime.undefined )) ? (haxe.lang.Runtime.toString(__fn_float1)) : (haxe.lang.Runtime.toString(__fn_dyn1)) );
		//line 214 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Diff.hx"
		java.lang.Object change = haxe.root.Reflect.field(haxe.lang.Runtime.getField(this.obj, "c", true), f2);
		//line 215 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Diff.hx"
		if (( change instanceof haxe.root.Array )) 
		{
			//line 216 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Diff.hx"
			if (haxe.lang.Runtime.eq(haxe.lang.Runtime.getField(change, "length", true), 2)) 
			{
				//line 218 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Diff.hx"
				this.changes.set(f2, change);
			}
			else
			{
				//line 221 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Diff.hx"
				haxe.root.Array<haxe.root.Array> tmp2 = connect.util.Diff.parseArray(((haxe.root.Array<haxe.root.Array>) (change) ));
				//line 221 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Diff.hx"
				this.changes.set(f2, tmp2);
			}
			
		}
		else
		{
			//line 225 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Diff.hx"
			connect.util.Diff tmp3 = connect.util.Diff.parse(change);
			//line 225 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Diff.hx"
			this.changes.set(f2, tmp3);
		}
		
		//line 213 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/util/Diff.hx"
		return null;
	}
	
	
	public java.lang.Object obj;
	
	public haxe.ds.StringMap changes;
	
}


