// Generated by Haxe 4.0.5
package connect.logger;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class LoggerConfig extends connect.Base
{
	public LoggerConfig(haxe.lang.EmptyObject empty)
	{
		//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
		super(haxe.lang.EmptyObject.EMPTY);
	}
	
	
	public LoggerConfig()
	{
		//line 50 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
		connect.logger.LoggerConfig.__hx_ctor_connect_logger_LoggerConfig(this);
	}
	
	
	protected static void __hx_ctor_connect_logger_LoggerConfig(connect.logger.LoggerConfig __hx_this)
	{
		//line 51 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
		__hx_this.path_ = "logs";
		//line 52 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
		__hx_this.level_ = connect.logger.Logger.LEVEL_INFO;
		//line 53 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
		__hx_this.handlers_ = new connect.util.Collection<connect.logger.LoggerHandler>().push(new connect.logger.LoggerHandler(new connect.logger.MarkdownLoggerFormatter(), new connect.logger.FileLoggerWriter()));
	}
	
	
	public connect.logger.LoggerConfig path(java.lang.String path)
	{
		//line 21 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
		this.path_ = path;
		//line 22 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
		return this;
	}
	
	
	public connect.logger.LoggerConfig level(int level)
	{
		//line 33 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
		this.level_ = level;
		//line 34 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
		return this;
	}
	
	
	public connect.logger.LoggerConfig handlers(connect.util.Collection<connect.logger.LoggerHandler> handlers)
	{
		//line 45 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
		this.handlers_ = handlers.copy();
		//line 46 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
		return this;
	}
	
	
	public java.lang.String path_;
	
	public int level_;
	
	public connect.util.Collection<connect.logger.LoggerHandler> handlers_;
	
	@Override public double __hx_setField_f(java.lang.String field, double value, boolean handleProperties)
	{
		//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
		{
			//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
			boolean __temp_executeDef1 = true;
			//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
			if (( field != null )) 
			{
				//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
				switch (field.hashCode())
				{
					case -1106127525:
					{
						//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
						if (field.equals("level_")) 
						{
							//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
							__temp_executeDef1 = false;
							//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
							this.level_ = ((int) (value) );
							//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
							return value;
						}
						
						//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
			if (__temp_executeDef1) 
			{
				//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
				return super.__hx_setField_f(field, value, handleProperties);
			}
			else
			{
				//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_setField(java.lang.String field, java.lang.Object value, boolean handleProperties)
	{
		//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
		{
			//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
			boolean __temp_executeDef1 = true;
			//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
			if (( field != null )) 
			{
				//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
				switch (field.hashCode())
				{
					case 64142102:
					{
						//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
						if (field.equals("handlers_")) 
						{
							//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
							__temp_executeDef1 = false;
							//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
							this.handlers_ = ((connect.util.Collection<connect.logger.LoggerHandler>) (value) );
							//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
							return value;
						}
						
						//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
						break;
					}
					
					
					case 106438874:
					{
						//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
						if (field.equals("path_")) 
						{
							//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
							__temp_executeDef1 = false;
							//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
							this.path_ = haxe.lang.Runtime.toString(value);
							//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
							return value;
						}
						
						//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
						break;
					}
					
					
					case -1106127525:
					{
						//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
						if (field.equals("level_")) 
						{
							//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
							__temp_executeDef1 = false;
							//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
							this.level_ = ((int) (haxe.lang.Runtime.toInt(value)) );
							//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
							return value;
						}
						
						//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
			if (__temp_executeDef1) 
			{
				//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
				return super.__hx_setField(field, value, handleProperties);
			}
			else
			{
				//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
		{
			//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
			boolean __temp_executeDef1 = true;
			//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
			if (( field != null )) 
			{
				//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
				switch (field.hashCode())
				{
					case 64142102:
					{
						//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
						if (field.equals("handlers_")) 
						{
							//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
							__temp_executeDef1 = false;
							//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
							return this.handlers_;
						}
						
						//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
						break;
					}
					
					
					case 3433509:
					{
						//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
						if (field.equals("path")) 
						{
							//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
							__temp_executeDef1 = false;
							//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "path")) );
						}
						
						//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
						break;
					}
					
					
					case -1106127525:
					{
						//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
						if (field.equals("level_")) 
						{
							//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
							__temp_executeDef1 = false;
							//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
							return this.level_;
						}
						
						//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
						break;
					}
					
					
					case 102865796:
					{
						//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
						if (field.equals("level")) 
						{
							//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
							__temp_executeDef1 = false;
							//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "level")) );
						}
						
						//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
						break;
					}
					
					
					case 106438874:
					{
						//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
						if (field.equals("path_")) 
						{
							//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
							__temp_executeDef1 = false;
							//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
							return this.path_;
						}
						
						//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
						break;
					}
					
					
					case 2069097:
					{
						//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
						if (field.equals("handlers")) 
						{
							//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
							__temp_executeDef1 = false;
							//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "handlers")) );
						}
						
						//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
			if (__temp_executeDef1) 
			{
				//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public double __hx_getField_f(java.lang.String field, boolean throwErrors, boolean handleProperties)
	{
		//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
		{
			//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
			boolean __temp_executeDef1 = true;
			//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
			if (( field != null )) 
			{
				//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
				switch (field.hashCode())
				{
					case -1106127525:
					{
						//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
						if (field.equals("level_")) 
						{
							//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
							__temp_executeDef1 = false;
							//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
							return ((double) (this.level_) );
						}
						
						//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
			if (__temp_executeDef1) 
			{
				//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
				return super.__hx_getField_f(field, throwErrors, handleProperties);
			}
			else
			{
				//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_invokeField(java.lang.String field, java.lang.Object[] dynargs)
	{
		//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
		{
			//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
			boolean __temp_executeDef1 = true;
			//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
			if (( field != null )) 
			{
				//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
				switch (field.hashCode())
				{
					case 2069097:
					{
						//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
						if (field.equals("handlers")) 
						{
							//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
							__temp_executeDef1 = false;
							//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
							return this.handlers(((connect.util.Collection<connect.logger.LoggerHandler>) (dynargs[0]) ));
						}
						
						//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
						break;
					}
					
					
					case 3433509:
					{
						//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
						if (field.equals("path")) 
						{
							//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
							__temp_executeDef1 = false;
							//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
							return this.path(haxe.lang.Runtime.toString(dynargs[0]));
						}
						
						//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
						break;
					}
					
					
					case 102865796:
					{
						//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
						if (field.equals("level")) 
						{
							//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
							__temp_executeDef1 = false;
							//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
							return this.level(((int) (haxe.lang.Runtime.toInt(dynargs[0])) ));
						}
						
						//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
			if (__temp_executeDef1) 
			{
				//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
				return super.__hx_invokeField(field, dynargs);
			}
			else
			{
				//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<java.lang.String> baseArr)
	{
		//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
		baseArr.push("handlers_");
		//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
		baseArr.push("level_");
		//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
		baseArr.push("path_");
		//line 14 "/home/travis/build/cloudblue/connect-haxe-sdk/connect/logger/LoggerConfig.hx"
		super.__hx_getFields(baseArr);
	}
	
	
}


